### ISSUE TITLE
Physics universal function to calculate interface pressure - p_int

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1001]
A function is needed to calculate pressure at cell interfaces (given pressure at cell centers) in Pa

There is guidance on what this algorithm looks like here:

https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/2605384045/Vertical+Coordinate?focusedCommentId=2605417001#comment-2605417001

**Comment by bartgol** [comment]
I'm not sure scream should do this. Pressure is constant over a physics step, so there's no _need_ to compute this in scream. Dynamics should provide p_int, using whatever algorithm it deems appropriate.

That said, we _do_ need to decide how p_int should be computed, since Homme naturally provides pressure only at midpoints.

**Comment by bartgol** [comment]
I'm going to close this, since I think we agreed this should not be done, because of the complicated way in which the dycore ensures the surface no penetration boundary condition.

**Comment by PeterCaldwell** [comment]
I think we agreed to revisit p_int as a universal function for v1.1 (see #1035 ) but are giving up on it for v1 because of the complications Luca mentioned.

**Comment by bartgol** [comment]
Side comment: the nh pressure has the big problem of having the top bc alongside being involved in the no-penetration bc at the surface (unlike, say, T_int, where we only have a bc at the bottom). Dynamics has a relatively involved way of ensuring the surface pressure is compatible with the bc. I doubt we can have a p_int routine that does a similar job outside of dyn.
