### ISSUE TITLE
P3: Add qiberg to cmeiout in P3 

### ISSUE THREAD

**Issue by hassanbeydoun** [E3SM-Project/scream#122]
qiberg is effectively a tendency removing qc and adding qitot. However, since qiberg is a vapor deposition term, it potentially needs to be added to cmeiout (needed by E3SM).

**Comment by AaronDonahue** [comment]
for context:

```real(rtype), intent(out), dimension(its:ite,kts:kte) :: cmeiout ! qitend due to deposition/sublimation```

```cmeiout(i,k) = qidep - qisub + qinuc```

```qitot(i,k) = qitot(i,k) + (qidep+qinuc+qiberg)*dt + dum```

so `qiberg` is part of the ice tendency and is related to the deposition rate, but the variable `cmeiout` doesn't include `qiberg` as of yet.

**Comment by bartgol** [comment]
@AaronDonahue is this still a todo item or can we close?

**Comment by AaronDonahue** [comment]
Hmmm, good question.  I'm not sure.  I'm going to ping (assign) this to Hassan and Peter and give them the final say.

**Comment by PeterCaldwell** [comment]
My feeling is that cmeiout (=condensation minus evaporation for ice) should really just be set to vap_ice_exchange: it is meant to be the net mass transfer from vapor to/from ice phase. Since qiberg in a practical sense takes from cloud liquid rather than vapor, I don't think it should be included. But the answer to this might depend on what cmeiout is being used for outside of P3... which I don't know. @hassanbeydoun - do you disagree with this assessment?

More nitpicky: I see at https://github.com/E3SM-Project/scream/blob/db22c9825428036b8b0075749593643cc64ece62/components/cam/src/physics/cam/micro_p3.F90#L837 that cmeiout *is* actually identical to vap_ice_exchange... so the cmeiout variable is extraneous and should be removed (if my prev paragraph is right). 

More troublingly, on https://github.com/E3SM-Project/scream/blob/db22c9825428036b8b0075749593643cc64ece62/components/cam/src/physics/cam/micro_p3_interface.F90#L1125 in p3_interface, we seem to be adding cmeiout to vap_liq_exchange even though it is really vap_ice exchange. I think vap_liq_exchange is just written to history, but this still seems like a bug.

**Comment by hassanbeydoun** [comment]
cmeiout is identical to vap_ice_exchange. We added qiberg to liq_ice_exchange in keeping with @PeterCaldwell 's argument. @PeterCaldwell I believe we are adding cmeliq to vap_liq_exchange and to cmeiout?

**Comment by AaronDonahue** [comment]
@hassanbeydoun and @PeterCaldwell is this still an issue?  Can we delete?
