### ISSUE TITLE
Update SNL machines that use sems modules

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1227]
At SNL, the `sems-env` modules are now deprecated, and will be removed by the end of the calendar year. We need to update the machines using it (as of today, only mappy does).

**Comment by jgfouca** [comment]
Yeah, we'll need to move to the new modules and potentially install missing packages. The new system won't have as many tuples in it. I can handle this since I have experience with the TPLs.

**Comment by jgfouca** [comment]
The V1 SEMS TPLs have been archived and should remain available indefinitely. I actually prefer the V1 system over the V2 system (not surprising since I created the V1 system) for a number of reasons including better support for project-specific TPLs. Barring something unforeseen, I would like to stay with V1 indefinitely, so I am closing this ticket.
