### ISSUE TITLE
P3: Reconsider adding qcheti to qirim

### ISSUE THREAD

**Issue by hassanbeydoun** [E3SM-Project/scream#123]
I realize qcheti being added to qirim was part of the original code, but I think we should consider removing it. qcheti represents ice nucleation of cloud drops which in the physical world results in small ice crystals (not rime/graupel).

**Comment by AaronDonahue** [comment]
for context: 
`real(rtype), intent(out),   dimension(its:ite,kts:kte)      :: cmeiout    ! qitend due to deposition/sublimation`
`cmeiout(i,k) = qidep - qisub + qinuc`
`qitot(i,k) = qitot(i,k) + (qidep+qinuc+qiberg)*dt + dum`

so qiberg is part of the ice tendency and is related to the deposition rate, but the variable `cmeiout` doesn't include `qiberg` as of yet.

**Comment by bartgol** [comment]
Is this still relevant? @AaronDonahue @hassanbeydoun

**Comment by PeterCaldwell** [comment]
I agree with this argument. In addition to @hassanbeydoun 's opinion, I'd like to know what @JS-WRF-SBM thinks.

**Comment by JS-WRF-SBM** [comment]
@PeterCaldwell @hassanbeydoun 

I think we should ask the same question regarding the frozen droplets (cloud) and the frozen drops (rain). 
P3 distinguishes between 'deposition' and rimed masses contribution, so the total ice mass (per category) is defined by:
`qitot = qi_dep + qi_rim`
The 'deposition' portion is treated as unrimed particles, so if we will increase that mass portion, the overall bulk density could in principle decrease (based on unrimed m-D relation for large ice crystals), although frozen droplet/drops were added to this grid-cell ice population -- this is a conceptual contradiction.

Therefore, in order to more precisely prognose the density, both freezing droplets and drops are treated as rimed mass contribution, which includes correcting the rimed and volume parts of the code.

Overall, I would keep the code in tact for this part.

**Comment by AaronDonahue** [comment]
From @hassanbeydoun : "close. Stay consistent with liq to ice transitions considered as rime"
