### ISSUE TITLE
Scope out possibility of specialized version of field requests for tracer fields.

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1478]
Tracers are a more specialized version of fields, and come in different flavors. One important distinction is whether they are "water based" or not (i.e., if they can be wet/dry or not). Currently, atmosphere processes (APs) can only request "fields", via FieldRequest objects, and the atm driver (AD) will have zero knowledge of what kind of field it is. The only tool that APs can use to tag a field (e.g., as a tracer) is to add the field to certain groups. There's no limit to the labels that one can add to a field; any string will do (though these strings are used as case-insensitive strings).

This poses an issue when it comes to add new tracers: if an AP adds tracer "foo", which is water-based, in order to trigger wet<->dry conversion (by the way, SCREAM _assumes_ all tracers to be wet in the Field Manager), the AP needs to add the "water_based" label (this label is for show only, we haven't implemented this group yet, but there _will_ be some sort of label to achieve this goal), meaning add "foo" to the group "water_based" _on top of the group_ "tracers". If AP forgets to add one of the two, "foo" will not be dealt with correctly (without "tracer", it won't be advected, and without "water_based" it won't undergo wet<->dry conversion).

We might want to scope out some special syntax/interface options to allow APs to issue FieldRequest' objects specifically for tracers. E.g., we could

1. Add `bool tracer` and `bool water_based` to `FieldRequest`, both defaulting to false.
2. Add `add_tracer` methods to `AtmosphereProcess`, which an AP can use to request a field that happens to be a tracer. These methods will automatically set `tracer=true`, and will require to pass a value for `water_based`. After that, they will call the basic `add_field` methods.

Better yet, we could make `water_based` an enum, so that if someone uses the existing `add_field` methods to add a tracer, without setting `water_based` in the field request, the AD can issue an error.

Tagging folks who were part of AD design/discussions in the past, to get their opinions: @AaronDonahue @jeff-cohere @tcclevenger @PeterCaldwell @brhillman

**Comment by singhbalwinder** [comment]
TKE is the only one I found so far. I thought it cannot participate in wet<->dry conversion, so I discussed this with @bartgol and @AaronDonahue . In P3, we work with individual tracers, so it was never an issue there. In SHOC, we grab all the tracers (including TKE) in an array. It is up to us to define which element of that array will participate in wet<->dry conversion or not. That is the reason we were thinking of "taggging" tracers to specify whether they can participate in wet<->dry conversion or not.

**Comment by PeterCaldwell** [comment]
Since TKE is actually defined per kg of air, it seems like there is a correct answer for "should TKE be defined with respect to total air or dry air". My recollection is that the dycore wants quantities defined relative to total air in order to do advection right. If so, I don't see why TKE should be treated any differently... it should also be wet for advection. I'm not sure whether we'd want it to be dry for use in SHOC though...

**Comment by singhbalwinder** [comment]
Thanks Peter. It at least makes our FM consistent that all tracers in FM are wet. 

@bogensch: Do you know what SHOC expects for TKE  (wet or dry) when all other tracers (q, qc, qi etc.) in SHOC are in dry mmrs.

**Comment by bogensch** [comment]
Based on a conversation I had with Peter yesterday and perusing the code, it seems that currently SHOC in SCREAM is being fed and using wet TKE (I feel awkward saying that since I don't think of as TKE as wet or dry haha).

**Comment by bogensch** [comment]
I'm mildly to moderately embarrassed that I don't know what SHOC expects for TKE regarding wet vs dry.  My reasoning for the above statement was that the dycore is advecting TKE as wet, which gets passed to SHOC... and since TKE is not an explicit function of pressure or vapor or clouds then it would stay as wet when in the domain of the SHOC parameterization, right?  Though, TKE is a function of the buoyancy flux, which is a function of the cloud liquid mixing ratio... so not sure if that's an argument for SHOC to expect TKE as dry since cloud liquid mixing ratio is dry?

**Comment by bartgol** [comment]
I'm gonna close this, since it appears the driving use case for SHOC found an alternative solution.
