### ISSUE TITLE
Unknown input.yaml options are silently ignored

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1493]
https://github.com/E3SM-Project/scream/pull/1491#pullrequestreview-915007284 made me realize that if we make a typo in a parameter name in our input.yaml, SCREAMv1 will just silently ignore that parameter setting and use its default value instead. This is dangerous. We should instead error out if our yaml parser encounters a value it doesn't know what to do with. 

Our solution to this problem might be different once users only interact with the model via xml (because then all parameters must have defaults defined in easily-queryable xml so we can compare parameters against available options). My suggestion in the meantime is to turn the yaml file into a list (or maybe a list for each heading), then pop each parameter out of the list as it is used. If there are any parameters left over that didn't get used, complain and die. 

@jgfouca - this seems relevant to you...

**Comment by bartgol** [comment]
In Trilinos, ParameterList offers a "validate" method, which takes in another parameter list. If the current PL contains parameters that are not in the valid list, it craps out. This is what trilinos does (more or less)

```
   ParameterList my_list; // contains "Param 1" and "Parm 2" keys (notice typo);
   ParameterList valid_list; // contains "Param 1" and "Param 2"
   
   my_list.validateParameters(valid_list); // this should throw
```
In order to do this, we need all classes to provide a list of valid inputs (so that it can be run "agnostically"). This is a bit problematic when sublists names depend on other parameters values (e.g., the name of a grid or of an atm process). An alternative is to have our classes perform these checks as soon as parameters are set.

**Comment by PeterCaldwell** [comment]
Yeah, the difficulty of getting a list of valid inputs is why I thought it might be simpler to just ask whether there were some parameters in input.yaml which weren't actually used... but maybe the solution is to just move to Jim's new xml frontend and not worry about this...

**Comment by bartgol** [comment]
Notice that our parser swallows all the parameters. The parser has no clue what each parameter/sublist is, nor whether it will be used. The burden of checking the inputs relies solely on the classes that _use_ the parameter lists. Imho, checking parameter/sublists names is a healthy thing to do. There are some classes that could do this.

**Comment by jgfouca** [comment]
@PeterCaldwell , the new system is very close to done, so let's move this discussion to the #1462
