### ISSUE TITLE
PIO ERROR: could not find variable p_int in file when trying to use ne30 for certain stand-alone tests

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1514]
When I make a change such as this:
```
    #Filename: rrtmgp_init_ne2np4.nc
    Filename: /global/cfs/cdirs/e3sm/ndk/screami_ne30np4L72_20220317.nc
```

Some of the stand-alone tests fail like:

```
login05% ./rrtmgp_standalone
Calling initialize_kokkos
 ExecSpace name: Cuda
 ExecSpace initialized: yes
 active avx set: -AVX2-AVX
 compiler id: GCC
 default FPE mask: 0 (NONE) 
 #host threads: 1


-------- EKAT CONFIGS --------

 ExecSpace name: Cuda
 ExecSpace initialized: yes
 active avx set: -AVX2-AVX
 compiler id: GCC
 default FPE mask: 0 (NONE) 
 #host threads: 1

-------- SCREAM CONFIGS --------

 sizeof(Real) = 8
 default pack size = 1
-------------------------------

Starting catch session on rank 0 out of 1
     -49                                                                                                PIO ERROR: could not find variable p_int in file /global/cfs/cdirs/e3sm/ndk/screami_ne30np4L72_20220317.nc
MPICH Notice [Rank 0] [job id ] [Tue Mar 29 10:33:50 2022] [login05] - Abort(-49) (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -49) - process 0
```

**Comment by AaronDonahue** [comment]
Right, this is similar to the discussion we were having on Slack.  The initial condition file you are using assumes that homme will run, which will also produce `p_int`.  But in standalone mode this isn't the case.  So we need a different file.  I would expect this to be the case with most of the physics since the dependency on `p_int` or `p_mid` is pretty common.

**Comment by ndkeen** [comment]
Yes, I'm just making an issue as I thought it might be helpful. Feel free to close if it's not needed. Or rename, etc.

**Comment by AaronDonahue** [comment]
presumably yes

**Comment by ndkeen** [comment]
Is there a path forward for this (and I missed something) or do we still not know best way to handle this?  If we could fix this, we could maybe run stand-alone tests with cime-ne30-like sizes.

**Comment by bartgol** [comment]
We could modify our input files, adding the missing vars. We have a python script to (somewhat) easily import fields from other ncfiles (checking dims and all). But it would require updating the files stored on the server. I could mod the files, and ask anyone with e3sm inputdata access to upload them.

**Comment by PeterCaldwell** [comment]
If I recall correctly, the problem you're having with ne30 non-homme standalone tests is that you're trying to use one of Ben's screami initial condition file mean for CIME runs instead of the initial condition file which Aaron created which is specific for each individual unit test you want to run. So an easy solution would be to just use Aaron's old code to write an ne30 IC for the particular test you're interested in. The other solution would be to add _all_ input variables requested by _any_ standalone unit test to Ben's screami files. Then we'd have a single skeleton key input file which would work for anything. I worry that this skeleton key file would end up getting really bloated though, which is a problem since these files are also how we initialize our CIME runs. Do we know how many variables are needed for standalone unit tests which aren't in the FM?

Another benefit of the skeleton key is that it would allow us to switch process order and rerun without needing a different IC file.

**Comment by ndkeen** [comment]
I think this is now resolved as Ben created some new IC files with missing var (and I tested w several stand-alone tests).
