### ISSUE TITLE
add atm-config-chg --append type option

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1564]
For the XML control, if an entry isn't set originally in the `/cime_config/namelist_defaults_scream.xml` file it cannot be added to the `namelist_scream.xml` in the case_scripts directory in any way, including by manually adding the entry to the file.  The reason is that there is no `metadata for child X`.

It might be nice to be able to `append` an entry to an XML category using `atm-config-chg` so that we don't have to set defaults for every possible argument in our `/cime_config/namelist_defaults_scream.xml` file.

Here is a use case that I ran into that might illustrate what I mean.  I wanted to subcycle a few processes in my run.  To do this I needed to add `Number of Subcycles` to the process itself, so taking something like this in the original `namelist_scream.xml` file

```
          <Process__0>
            <Process__Name>SHOC</Process__Name>
            <Enable__Postcondition__Checks>True</Enable__Postcondition__Checks>
            <Enable__Precondition__Checks>True</Enable__Precondition__Checks>
            <Grid>Physics GLL</Grid>
          </Process__0>
```

and adding

```
          <Process__0>
            <Process__Name>SHOC</Process__Name>
            <Number__of__Subcycles>6</Number__of__Subcycles>
            <Enable__Postcondition__Checks>True</Enable__Postcondition__Checks>
            <Enable__Precondition__Checks>True</Enable__Precondition__Checks>
            <Grid>Physics GLL</Grid>
          </Process__0>
```

But the original namelist defaults didn't have that entry to begin with, so `buildnml` throws an error.   So instead I needed to go back to the main code and add the option to the main defaults list and rebuild the whole case.

**Comment by bartgol** [comment]
#1521 adds the subcycling info to the "generic" atm proc XML entry.

I find the `append` option a bit dangerous, since it requires to skip validation, which kind of defies the purpose of half of the XML infrastructure. If one needs an entry that is not in the XML default, probably they need to update the XML defaults file...

I vote for not adding the feature, unless some really extraordinary need arises.

**Comment by PeterCaldwell** [comment]
Interesting use case. Having xml entries without a default not be dumped into namelist_scream.xml was a feature we added to prevent the code seen by users from becoming too bloated (e.g. if I'm running SHOC, why should I see CLUBB parameter choices?). Separately, we implemented the check that anything you add to namelist_scream.xml matches an existing setting in namelist_defaults because we wanted to protect against cases where you mistyped the option you wanted and think the model is using it when it isn't (e.g. I told the model to run with `dt=1 sec` so how could I have known that `dtime was 1800 sec`). I was always implicitly assuming that if a user really wanted to add an xml setting that wasn't included by default, that they'd be able to. Substepping is a great example. I think we probably *do* want an "expert mode" for this... one where users can easily do what they want, but they know that the guardrails are off so they should triple check their options.

**Comment by bartgol** [comment]
Peter, I think we're mixing up things. In your example, CLUBB parameters will not be dumped to `namelist_scream.xml` if the current compset does not use CLUBB. Perhaps this is not true in current master, but #1521 has a different approach: when building `namelist_scream.xml`, it grabs sections from `namelist_defaults_scream.xml` depending on the compset. So if the compset uses an atm procs list `(homme,shoc,p3)`, the section for CLUBB (assuming there is one) in the defaults XML file will be completely ignored.

I think the issue here is that a parameter that _should_ have been in the XML defaults was, in fact, not there. In such a case, we _should_ update the XML defaults file. I can't foresee an example where we _don't want_ a parameter to be in the XML defaults file, and yet we _do want_ users to be able to set them in the case. Do we think such a case will ever happen?

And by the way, substepping will be supported by the second version of our XML defaults.

**Comment by AaronDonahue** [comment]
Yeah, this is the other option.  That every possible option will be added to every category that can have that option with a default. Which will make the namelist_defaults file a bit long, but maybe that won't be a problem.  Note, this means that every process that is added as an option will need to have the subcycles option (even if the default will usually be 1).  

To push back a little on the question of whether or not we ever anticipate having an option that isn't given a default.  I think the substepping is a good example.  In order to have defaults we will need to have Number of Subcycles added to all of the process sections, and we will need to add the same syntax to the main Atmosphere__Process section.  Because we will have to anticipate every location where it would be valid to subcycle.

On top of that.  If I wanted to add a group of subprocesses that wasn't already defined by default in the namelist_defaults.xml file, so that I can subcycle this group, it isn't clear to me that this would be acceptable.  Since now I would have a deeper level of processes then I've ever listed in the default file.  That alone may throw an error, but even if it doesn't having a deeper level means that there will be no metadata.  Essentially we lose that 'expert' ability to adjust things like subcylce (or in the future parallel) groups at runtime.  We will need to update the namelist defaults in the code itself and rebuild before we can make these kind of advanced adjustments.  Maybe thats not a problem that we anticipate needing an full blown solution for though.

**Comment by bartgol** [comment]
I don't want to kill the conversation, but I would like to reiterate again that #1521 is changing the way we add defaults, and makes the subcycling option available.

That PR creates "inheritance" between defaults, to allow, for instance, to set "generic" parameters for _all_ atm processes. 

Here's the atm procs section of the new XML file, to explain the concept

```
  <atmosphere_processes_defaults>

    <!--
      List of atm procs. You can form processes groups by using parentheses,
      or by giving the group a name, and adding a subsection that inherit
      from atm_proc_group. atm_procs_list itself *must* represent a group,
      so it must be of the form (a,b,...).
      NOTE: *CANNOT* be changed.
    -->
    <!-- <atm_procs_list>(homme,((shoc,cldFraction,spa,p3),rrtmgp))</atm_procs_list> -->
    <atm_procs_list locked="true">(homme,physics)</atm_procs_list>

    <!-- Basic options for each atm process -->
    <atm_proc_base>
      <Num__Subcycle__Iterations>1</Num__Subcycle__Iterations>
      <Enable__Precondition__Checks type="logical">true</Enable__Precondition__Checks>
      <Enable__Postcondition__Checks type="logical">true</Enable__Postcondition__Checks>
    </atm_proc_base>

    <!-- Basic options for each atm process group -->
    <atm_proc_group inherit="atm_proc_base">
      <atm_procs_list>ERROR_NO_ATM_PROCS</atm_procs_list>
      <Type>Group</Type>
      <Schedule__Type>Sequential</Schedule__Type>
    </atm_proc_group>

    <!-- Basic options for each "physics" atm process -->
    <physics_proc_base inherit="atm_proc_base">
      <Grid>Physics GLL</Grid>
    </physics_proc_base>

    <!-- Homme dynamics -->
    <homme inherit="atm_proc_base">
      <Grid>Dynamics</Grid>
      <Vertical__Coordinate__Filename>${DIN_LOC_ROOT}/atm/scream/init/init_ne4np4.nc</Vertical__Coordinate__Filename>
      <Vertical__Coordinate__Filename COMPSET=".*SCREAM%AQUA.*">${DIN_LOC_ROOT}/atm/scream/init/scream-aquaplanet_init_ne4np4_L72_20211202.nc</Vertical__Coordinate__Filename>
      <Moisture>moist</Moisture>
    </homme>

    <!-- P3 microphysics -->
    <p3 inherit="physics_proc_base"/>

    <!-- SHOC macrophysics -->
    <shoc inherit="physics_proc_base"/>

    <!-- CLD fraction -->
    <cldFraction inherit="physics_proc_base"/>

    <!-- Simple Prescribed Aerosols (SPA) -->
    <spa inherit="physics_proc_base">
      <SPA__Remap__File>none</SPA__Remap__File>
      <SPA__Data__File>${DIN_LOC_ROOT}/atm/scream/init/spa_file_unified_and_complete_ne4_scream.nc</SPA__Data__File>
    </spa>

    <!-- Simple Prescribed Aerosols (SPA) -->
    <rrtmgp inherit="physics_proc_base">
      <active_gases>h2o, co2, o3, n2o, co, ch4, o2, n2</active_gases>
      <Orbital__Year>-9999</Orbital__Year>
      <Orbital__Eccentricity>-9999</Orbital__Eccentricity>
      <Orbital__Eccentricity COMPSET=".*SCREAM%AQUA.*">0</Orbital__Eccentricity>
      <Orbital__Obliquity>-9999</Orbital__Obliquity>
      <Orbital__Obliquity COMPSET=".*SCREAM%AQUA.*">0</Orbital__Obliquity>
      <Orbital__MVELP>-9999</Orbital__MVELP>
      <Orbital__MVELP COMPSET=".*SCREAM%AQUA.*">0</Orbital__MVELP>
    </rrtmgp>

    <mac_aero_mic inherit="atm_proc_group">
      <atm_procs_list>(shoc,cldFraction,spa,p3)</atm_procs_list>
    </mac_aero_mic>

    <physics inherit="atm_proc_group">
      <atm_procs_list>(mac_aero_mic,rrtmgp)</atm_procs_list>
    </physics>
  </atmosphere_processes_defaults>
```

**Comment by PeterCaldwell** [comment]
Nice! I like the inheritance. 

I think if nothing else we shouldn't devote resources to this "expert mode" until we find another case where we would need it (since subcycling clearly isn't that case). My recollection is there are a lot of cases of stuff not in the default EAM namelist but which expert users can add, but I think this is due to having the code itself set the defaults if they aren't in the namelist. This seems like a terrible policy which we should do everything we can to avoid: talk about bad provenance!

So in the end I vote with Luca - we should not support an append/expert mode capability (at least until the unlikely event that we find a use case we can't resist).

**Comment by AaronDonahue** [comment]
Oh nice!  I like the inheritance.  That will solve my comment here.  I'll go ahead and close the issue then.
