### ISSUE TITLE
Expose physics parameters rather than having them hardcoded

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#1580]
Start with SHOC, then do P3.

**Comment by AaronDonahue** [comment]
@hassanbeydoun and @bogensch  have we largely accomplished this task?  Are there still SHOC or P3 params to expose?  If so, we should probably list them here or in a separate issue, that way we can reference a list as more params are exposed.

**Comment by bogensch** [comment]
SHOC is done

**Comment by hassanbeydoun** [comment]
So is P3.

From: Peter Bogenschutz ***@***.***>
Date: Thursday, November 14, 2024 at 11:35 AM
To: E3SM-Project/scream ***@***.***>
Cc: Beydoun, Hassan ***@***.***>, Mention ***@***.***>
Subject: Re: [E3SM-Project/scream] Expose physics parameters rather than having them hardcoded (Issue #1580)

SHOC is done

**Comment by AaronDonahue** [comment]
Awesome, thanks.  Closing now
