### ISSUE TITLE
post-cond error at ne120 with Intel -- Property check name: nc within interval

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1591]
This is the error I see with ne120 using intel compiler on cori when turning off SPA. Must still be init or on the first step.

```
 529: terminate called after throwing an instance of 'std::logic_error'
 529:   what():  /global/cfs/cdirs/e3sm/ndk/se02-apr27/components/scream/src/share/atm_process/atmosphere_process.cpp:287: FAIL:
 529: false
 529: Error! Failed post-condition check (cannot be repaired).
 529:   - Atm process name: Microphysics
 529:   - Property check name: nc within interval [0, 1e+09]
 529:   - Atmosphere process MPI Rank: 529
 529:   - Error message: FieldWithinIntervalCheck failed; min = 0.000000; max = 1203820506.525065
```

**Comment by PeterCaldwell** [comment]
I think when SPA is off, nc is just getting permanently set to the values it reads from the v0 initial condition file... so apparently the max nc isn't big enough. The fix for this is changing the max nc bound to 1e11 in https://github.com/E3SM-Project/scream/blob/19d457f0f3f0668cd694659698ac5a58b408d6ac/components/scream/src/physics/p3/atmosphere_microphysics.cpp#L184 .

**Comment by PeterCaldwell** [comment]
This will be fixed as a side effect of #1596 (which just makes the change I suggest above).

**Comment by ndkeen** [comment]
After bringing in those relevant changes from PR 1596, I now see the following error with Intel:

```
1200: terminate called after throwing an instance of 'std::logic_error'
1200:   what():  /global/cfs/cdirs/e3sm/ndk/se02-apr27/components/scream/src/share/atm_process/atmosphere_process.cpp:249: FAIL:
1200: false
1200: Error! Failed pre-condition check (cannot be repaired).
1200:   - Atm process name: Radiation
1200:   - Property check name: sfc_alb_dir_vis within interval [0, 1]
1200:   - Atmosphere process MPI Rank: 1200
1200:   - Message: FieldWithinIntervalCheck failed; min = 1.000000; max = 1.000000
1200:
```

Which I think is now the same as the fail with GNU in https://github.com/E3SM-Project/scream/issues/1592

**Comment by PeterCaldwell** [comment]
Oh shoot. I think Ben tried to tell me this would happen. I think it would be easy to change sfc_alb_dir_vis to be an inout variable instead of an input variable (but I don't know how to do that). Or better yet, can we add a postcondition check to surface coupling that corrects albedo? I think that would avoid having to change function interfaces.

**Comment by ndkeen** [comment]
I tried this case again with latest version of IC file: `/global/cfs/cdirs/e3sm/bhillma/scream/data/init/screami_ne120np4L72_20220503.nc` and I still get same error.

**Comment by ndkeen** [comment]
With the changes in PR1600, the case does run! It completes 11 steps before trying to write the first snapshot and then fails. I have this set to write every 12th step.

```
 32: PIO: FATAL ERROR: Aborting... FATAL ERROR: NetCDF: One or more variable sizes violate format constraints (file = SCREAMv1_output_hydrostatic.INSTANT.Steps_x12.np3072.0001-01-01.003000.nc)```
