### ISSUE TITLE
pre-condition error with GNU compiler at ne120 -- Property check name: sfc_alb_dir_vis within interval

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1592]
Error with GNU compiler on cori after turning off SPA. Must still be init or on the first step.

```
1585: terminate called after throwing an instance of 'std::logic_error'
1585:   what():  /global/cfs/cdirs/e3sm/ndk/se02-apr27/components/scream/src/share/atm_process/atmosphere_process.cpp:244: FAIL:
1585: false
1585: Error! Failed pre-condition check (cannot be repaired).
1585:   - Atm process name: Radiation
1585:   - Property check name: sfc_alb_dir_vis within interval [0, 1]
1585:   - Atmosphere process MPI Rank: 1585
1585:   - Message: FieldWithinIntervalCheck failed; min = 1.000000; max = 1.000000
```

**Comment by PeterCaldwell** [comment]
This is clearly a roundoff error: sfc_alb_dir_vis should be between 0 and 1 and is... 1. A quick fix would be to change false to true (i.e. repair out-of-bounds values rather than crash) in https://github.com/E3SM-Project/scream/blob/master/components/scream/src/physics/rrtmgp/atmosphere_radiation.cpp#L283 . You might have to do this for other sfc_albedo quantities too. A better(?) fix might be to increase the bounds on that line of code from 0 to 1 to an upper bound of 1+eps for small eps.

**Comment by PeterCaldwell** [comment]
@brhillman - do you have an opinion about whether repairing, setting bigger bounds, or something else should be our permanent fix?

**Comment by PeterCaldwell** [comment]
Note this is kinda the same issue as #1575

**Comment by ndkeen** [comment]
Yes, I saw that it was maybe the same thing as 1575, but this is without SPA and run the same way as the intel attempt https://github.com/E3SM-Project/scream/issues/1591

**Comment by PeterCaldwell** [comment]
Yeah, it's fine that they are separate issues, but the obvious solution in this issue is to allow repair since errors are just roundoff... but #1575 shows that doing so is dangerous because we *also* have cases where albedo is way outside the reasonable range. 

I'm beginning to wonder whether some of our surface components -> atm component mapping files are screwed up...

**Comment by ndkeen** [comment]
Can close this specific issue with #1596
