### ISSUE TITLE
SPA using significant memory at ne120

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1621]
On cori-knl, with ne120 (where we using ne30 SPA data and then a remapping file), the maximum total memory usage for a case with SPA was about 30% larger than a case without SPA. These 2 caes are using 128 nodes and 16 MPI's per node (no threads).
In these cases, they hit a known error after about 10 steps.

The first plot is without SPA.
![top_usedmem j58764206 n128](https://user-images.githubusercontent.com/5684727/167305790-ae71cd35-5fbc-4506-90c7-97eba9037be2.png)

Second plot uses SPA
![top_usedmem j58764104 n128](https://user-images.githubusercontent.com/5684727/167305792-13e56f68-d726-49db-8541-8acb245edfd8.png)

The x-axis is wall-clock time in seconds, which is why it would not look right to make these curves on the same plot.  Note the mem use during init stage for these 2 cases is also different.

I did something similar for 2 ne30 cases and I did not see a memory increase. Using master of around April 27th.

**Comment by bartgol** [comment]
Here's some *very* rough back of the envelope calculation.

With ne120 and nlev72 we have arrays for 3d fields of global length ne*ne*9*72=9.3M. With 128 ranks, that is about 73k entries/rank. Assuming O(100) fields in the FM, that is about 7.3M doubles per rank.

Now, SPA _does_ have a bad memory usage when it comes to initialization, where it reads some 60 global 2D fields _on each rank_. That amounts to roughtly 7.8M doubles per rank. However, I _think_ these global fields are thrown away after init time, and only local information is kept (so the 7.8M should go down to about 61k). This _could_ explain the higher initialization costs.

As for the runtime costs, there is one possible explanation. When running without SPA, all the aer_blah fields are loaded from file. With SPA, we keep in memory _two_ copies of these fields, to perform time interpolation. So the extra memory could be caused by those fields. To check, we have three swband 3d fields, and one lwband 3d field. That adds up to 14*3+16=58 extra 3d fields. I don't know if that should be as much as 30% of our memory footprint, but if my guess of O(100) fields in the FM is correct, then it's possible.

**Comment by PeterCaldwell** [comment]
Given the expected bad memory usage in SPA init, I would expect there to be a spike in memory usage towards the beginning of Noel's plot, then a sharp dropoff. It's interesting that the run with SPA does have a spike, but then jumps to even higher memory usage...

**Comment by ndkeen** [comment]
Just including the plots for ne30 on cori-knl without and with SPA. 
![top_usedmem j58763186 n11](https://user-images.githubusercontent.com/5684727/167515000-64059027-4ce7-4702-af1b-70769510fede.png)

![top_usedmem j58764208 n11](https://user-images.githubusercontent.com/5684727/167515021-133ea262-4c8f-4bc0-bba0-c92aad9c9754.png)

**Comment by bartgol** [comment]
Wow. It seems to suggest that spa uses zero additional memory? Something is amiss...

**Comment by PeterCaldwell** [comment]
I think the run with SPA at ne30 uses a tiny bit more memory than the run without it. 

Using Noel's highwater plots, I've got a crude answer to my earlier question of "what's our memory need per element in v1?": highwater_mem*num_nodes/total_num_elem. This is ~0.04GB/element for ne30, 0.05GB/element for ne120 without SPA, and 0.07 GB/element for ne120 with SPA.

**Comment by AaronDonahue** [comment]
I've been able to recreate this effect with ne4 and it is clear that SPA is a huge memory hog.  I'll dig deeper.

**Comment by ndkeen** [comment]
Great. I'm sure you see this, but for ne120, I see ~400MB jump after the call to `scorpio::set_decomp` on the remap file.

**Comment by AaronDonahue** [comment]
@ndkeen , yes, so far the evidence seems to point to the remap needing quite a lot of memory and then not letting it go when its done.

**Comment by AaronDonahue** [comment]
My current working theory is this:  We create temporary variables to store the entire set of remap data, which is pretty big.  By the end of the function we only keep the remap data needed by this MPI rank and discard the rest.

The theory is that something that should be discarded (i.e. free of memory) is in fact sticking around.  My best suspect is the PIO decomposition, which is something that SCORPIO creates and probably doesn't get destroyed just because a SPA function finishes.  Like the temporary Kokkos views we use to store the data in the function.

**Comment by AaronDonahue** [comment]
Because it's getting near the end of the day and I don't want to lose track, correspondence from Jayesh on Slack:
```
You need to call pio_freedecomp(pio_subsystem, iodesc)
```
I think that in the spa function where we get the remap data we need to also free the decomp for the variables that we only use temporarily.

**Comment by ndkeen** [comment]
Wow that's huge!  I was also following the slack discussions. Awesome. Any chance this hints at what might be the problem with memory growth for each snapshot output?

**Comment by PeterCaldwell** [comment]
This issue can be closed now, right Noel?

**Comment by ndkeen** [comment]
Sure
