### ISSUE TITLE
Need openmp build flags for the timers

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#1633]
After the PR to add better timer support to scream, I got the following fails with threads:

```
/usr/bin/ld: gptl.c:(.text+0x4361): undefined reference to `/global/common/software/nersc/pm-2021q4/sw/cmake-3.22.0/bin/cmake -E touch scream/src/mct_coupling/CMakeFiles/atm.dir/ekat_string_utils.F90.o.provides.build
omp_get_level'
```
Does seem odd that threaded builds were not using openmp flags at all (ie in any of our scream source builds)?

I was able to work-around this with something like:

```
if ("${PROJECT_NAME}" STREQUAL "E3SM")
  if (compile_threaded)
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
      string(APPEND CMAKE_C_FLAGS " -fopenmp")
      string(APPEND CMAKE_CXX_FLAGS " -fopenmp")
      string(APPEND CMAKE_Fortran_FLAGS " -fopenmp")
      string(APPEND CMAKE_EXE_LINKER_FLAGS " -fopenmp")
    else() #intel
      string(APPEND CMAKE_C_FLAGS " -qopenmp")
      string(APPEND CMAKE_CXX_FLAGS " -qopenmp")
      string(APPEND CMAKE_Fortran_FLAGS " -qopenmp")
      string(APPEND CMAKE_EXE_LINKER_FLAGS " -qopenmp")
    endif()
  endif()
endif()
```

**Comment by bartgol** [comment]
It might be related to the cmake interface target that scream builds in order to link against gptl. The gptl lib is created by CIME _before_ building e3sm, along with mct, share, scorpio, and maybe others. To make linking easier, I wrapped the lib in a cmake interface target, so that we only need to link it once, and we propagate target deps automatically.

However, I forgot to check for openmp. I don't think we should be hacking the CMAKE_<LANG>_FLAGS vars for this. We should be able to just add the openmp flag to the interface gptl target.

Question: do you get this only if Kokkos is built with OpenMP as backend, or do you get it even if Kokkos is built with Serial as backend? If it's only when Kokkos enables OpenMP (and I suspect the answer is yes), then we can fix it with one line in `components/scream/cmake/tpls/GPTL.cmake`:
```
      # Create the imported target that scream targets can link to
      add_library (gptl INTERFACE)
      target_link_libraries (gptl INTERFACE ${GPTL_LIB})
      target_include_directories (gptl INTERFACE ${INSTALL_SHAREDPATH}/include)     
+      include(EkatSetCompilerFlags)
+     SetOmpFlags (gptl C Fortran)
```

**Comment by ndkeen** [comment]
Looks like this is no longer an issue for me
