### ISSUE TITLE
Homme output from all ranks seems suppressed

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1705]
In EAM, I can put a statement like this in a HOMME file:
```F90
print *, hybrid%par%rank, 'hi'
```
and see output for every rank in e3sm.log. In EAMxx, I see output from rank 0 and sometimes another arbitrary rank in homme_atm.log, and that's it: there is nothing in e3sm.log.

This is a problem whenever one wants to output information from every rank, a common thing to do when debugging.

Interestingly, the `nsplit<1` warning shows that `printf` in a C++ file _does_ output to e3sm.log, including rank 0. So outputting to e3sm.log seems broken only for Fortran code in EAMxx dynamics.

**Comment by bartgol** [comment]
The homme log file is a hacky workaround. It all stems from not being able to have both C++ and F90 to write on the same file (atm.log). I mean, I think it's possible, but I suspect corruption of the log is all but certain with 2 concurrent file handles (and the online documentation about this niche case is scarce at best).

One thing that might be buggy is that I am not attaching/detaching stdout to/from homme.log at every homme iteration. I suspect this is wrong, since it might cause other stdout print statements to end up in other files (and vice versa). I suspect I need to attach stdout to file at the beginning of each c->f function in `src/dynamics/homme/interface/*` routine, and detaching at the end.

I also want to take the chance to ask if anyone has a different opinion on how to handle homme(xx) output. Should it be confined to homme_atm.log? Should it go directly to e3sm.log? The only option that I'm almost certain we can't do (but will take pointers to existing solutions, if any) is to send homme(xx) print statements to atm.log.

**Comment by sarats** [comment]
It's preferable to identify a more robust way.

@bartgol However if you want to hack your way writing to a log from both C++ and F90, make sure to call fflush() or [fsync](https://linux.die.net/man/2/fsync)() on the file descriptor and see if works (no corruption).

**Comment by ambrad** [comment]
@bartgol if this helps at all: Writing everything from ranks other than root to e3sm.log is perfectly fine and how EAM works. My understanding is that in EAM, e3sm.log captures everything not written to specific log file handles (`iulog` in the code), which is great for debugging.

**Comment by ambrad** [comment]
@bartgol sorry I missed this message. Yes, output from Homme to `*` as opposed to iulog ends up in e3sm.log. This may not be desired, but it's better than losing the output.

**Comment by ambrad** [comment]
Workaround: Use `write(0,*)` in F90 instead of `print`. Output then shows up in e3sm.log.

**Comment by PeterCaldwell** [comment]
Would it make sense for me to make a PR that swaps all the `print` commands in `components/homme/src/theta-l_kokkos/share/` for write(0,*)? I suspect lack of logging from non-masterproc tasks will often hinder our debugging (e.g. in #1728)...

**Comment by ambrad** [comment]
@PeterCaldwell I think it would be better to change the logger not to supress those statements.

**Comment by ambrad** [comment]
Luca pointed out that commenting out these two lines will also permit F90 stdout (and so `print *`) from all ranks to appear in e3sm.log:
https://github.com/E3SM-Project/scream/blob/fcf28ecbac2c4d5aab7c727b4834f89433b20ae2/components/scream/src/mct_coupling/atm_comp_mct.F90#L144-L145

**Comment by PeterCaldwell** [comment]
> just let homme's print statements go directly to es3m.log.

Yeah, that's my vote as a short-term solution as well. 

Longer term - It's pretty idiosyncratic to have some atm output go to atm.log but other atm output go to e3sm.log. I think we're gong to need to do *something* to unify atm logging. But let's save that for v1.1.

**Comment by ndkeen** [comment]
I think it would be unfortunate if `print*` and `write(*,*)` do not work as expected.

**Comment by bartgol** [comment]
There's a PR coming up that will fix (fingers crossed) the issues with print statements.
