### ISSUE TITLE
AT merge commit message enhancement

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1753]
@rljacob pointed out that the AT's merge commit message does not contain tags like "[BFB]", as is required in E3SM. Can the AT's message be made to include the first comment in the PR? If so, then PR authors can include the tag in that comment, as is required in E3SM anyway, and the AT will then transfer it to the commit message. This would follow standard integrator practice in E3SM.

**Comment by bartgol** [comment]
I've emailed AT maintainers on this. I suspect they will tell me this is not possible, so here are my suggestions on possible workarounds.

1. Disable automerge, and always merge manually, with a meaningful merge commits (in particular, with the BFB tag).
2. Keep automerge, and put meaningful tags in the PR title.

**Comment by bartgol** [comment]
I just talked to one of the AT maintainers. It turns out their AT2.0 is gonna be a continuation of the current one (rather than an overhaul), so they are accepting feature requests. However, the AT2.0 upgrade is their priority, and it is apparently a very large PR on their code, so they're swamped for _at least_ the next couple of months.

I brought up a few requests for our needs, one of which is the ability to modify the merge commit. In particular, I asked that all the PR labels be included in the merge commit (the AT already includes PR title and PR author), and they said it should be a 10 lines modification.

**Comment by rljacob** [comment]
forking might be the way to go because if you want to keep using AT when the repos are merged it will also have to know to merge to next and master.

**Comment by bartgol** [comment]
The AT can already handle two "target" branches, even though we have not experimented with it.

I forked the AT repo today, and made some adjustments. We will switch soon.

**Comment by bartgol** [comment]
I just switched our testing workflow to use a fork of the AT repo, where we added (among others) the feature that the PR labels are written in the merge commit msg.

Closing as resolved.
