### ISSUE TITLE
precipitation variables in P3 are incorrect when p3 is subcycled

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1755]
The two variables that track precipitation in P3 are `precip_liq_surf` and `precip_ice_surf`.  These are designated as "Computed" when added as fields in P3.  Which means the old `precip_X_surf` values are overwritten everytime P3 is called.

Those variables are not actually used until surface coupling is called.

In cases where P3 is subcycled we need to keep a cumulative value of `precip_liq_surf` and `precip_ice_surf` to pass to the surface.  Otherwise total water mass will not be conserved.

Note - this issue most likely impacts any "flux" type variable that could be substepped.

**Comment by AaronDonahue** [comment]
Summary of conversation via Slack with @bartgol -

The solution should be a mechanism by which and field that is a "flux" is able to accumulate until it is a) used or b) needs to be reset.  This can be accomplished by the following strategy

1. Change all fluxes in atmosphere processes from "Computed" to "Updated".  That way old values are retained and fluxes can be accumulated.
2. Add local flux calculations to the memory buffer for a process, that way we can track the local addition to the flux and simply add it to the overall flux in post-processing.
3. We need a way to check if a flux should be reset to 0.0.
  -  We could have the process that uses the flux reset it. 
  -  We could keep track of the timestamp for the beginning of timestep and check if this call to run_impl is at the beginning, if so reset the flux, if not, accumulate it.

The second approach is probably the safest, it avoids resetting a flux that may be used in more than one place, and avoids a separate process having to "know" to reset the flux.

**Comment by ambrad** [comment]
What does EAM do in this case?

**Comment by bartgol** [comment]
Imho, storing the atm timestep initial timestamp in each atm process, and have p3 check if `timestamp()==atm_timestep_start()` at the beginning of run_impl (and zero out fluxes if true), is the fastest way to achieve the desired result. Of course, all fluxes computation in p3 needs to be changed from `flux_blah = ...` to `flux_blah += ...`.

**Comment by AaronDonahue** [comment]
```
  // Note: if we are being subcycled from the outside, the host will set
  //       do_update=false, and we will not update the timestamp of the AP
  //       or that of the output fields.
  void set_update_time_stamps (const bool do_update);
```

@bartgol , does this comment and line mean that when subcycled the timestamp internal to this atmosphere process will not be updated be subcycle step?  Note this can be found on line 124 of `/components/scream/src/share/atm_process/atmosphere_process.hpp`

**Comment by AaronDonahue** [comment]
Another wrinkle in this issue, the precip fluxes are scaled by delta t.  Thus, we need too accumulate total precipitation and only scale by delta-t at the end of the timestep.  For example, if subcycling twice:

```
precip_total = precip_1 + precip_2
```
where,
```
precip_1 = precip(t_0)/dt_sub
precip_2 = precip(t_0+dt_sub)/dt_sub
```
so even if precip is constant across subcycles, say `precip(t_0)=precip(t_0+dt_sub)=P`, the total precip would be
```
precip_total = 2*P/dt_sub
->
precip_total = 4*P/dt
```
when it really should just be `2*P/dt`.  I see three options to solve:
1. We can rescale the subcycle precip flux to be actual precip, so multiply by dt_sub each subcycle.  Then, at the end of the timestep we scale the accumulated precip by the atmosphere dt to get a flux.
2.We can rescale the subcycle precip flux to be actual precip divided by the atmosphere timestep.  This is basically (1) but scaling by atmosphere dt each run_impl call instead of at the end of the timestep.
3. We scale the precip flux by the number of subcycles.

I like (1) or (2) more because it allows for dt_sub to be different per call to `run_impl` and feels safer than assuming that scaling by the number of subcycles is the right way to go.

**Comment by PeterCaldwell** [comment]
I usually think of the net flux from a bunch of substeps as the *average* flux over those substeps. This is effectively your option 3. My logic is that average flux is by definition the effective flux you'd have to use over the whole period to get the same answer as you'd get by summing over each substep. 

Your options 1 and 2 seem unnecessarily complex because they convert the flux in each substep into a total amount of water accumulated during those steps, then divide by the total elapsed time to get back to flux units. 

I guess this is a potato/potahtoh situation except that my impl requires less calculations ;-)

**Comment by bartgol** [comment]
So Peter, you're saying that when P3 detects it's the last subcycle steps it should do something like
```
precip_total += P/dt_sub; // last subcycle accumulation
precip_total /= num_subcycles; // compute avg flux
```
? That seems fairly simple to me. P3 can easily keep track of `num_subcycles` by keeping track of the timestamp.

**Comment by bartgol** [comment]
> 

Uhm, that seems to suggest that. And a quick look at the code seems to support that. I don't 100% recall why I implemented this involved mechanism. The code in `AtmosphereProcess::run` suggests it's because I do not update the atm proc timestamp between subcycles:
```
  // Let the derived class do the actual run
  auto dt_sub = dt / m_num_subcycles;
  for (m_subcycle_iter=0; m_subcycle_iter<m_num_subcycles; ++m_subcycle_iter) {
    run_impl(dt_sub);
  }

  if (m_params.get("Enable Postcondition Checks", true)) {
    // Run 'post-condition' property checks stored in this AP
    run_postcondition_checks();
  }

  m_time_stamp += dt; 
  if (m_update_time_stamps) {
    // Update all output fields time stamps
    update_time_stamps (); 
  }
```
The culprit was probably the atm proc group class: in it, the processes in the group would try to update the timestamp, but the timestamp was not moving forward in time, causing errors. Hence, I introduced this flag, to prevent processes from updating time stamps until the end of subcycling.

I suspect we could move the timestamp update in the for loop, so that we update by `dt_sub` at every subcycle. This should make everything work. I'll try it out quickly.

**Comment by PeterCaldwell** [comment]
Yes, I was advocating for `precip_total /= num_subcycles;` after the last substep. Note that this method won't work if different dt was used for different substeps (like in sedimentation, but not a problem here). 

Another even simpler option (which I think is a non-starter because it would require P3 calculations after P3 ends) is to have P3 return the amount of water precipitated in a step rather than the precipitation per second (ie a mass rather than a flux). Then you could just do 

`P+=P` inside the process
`precip_flux=P/whole_step_dt` after the last substep.

**Comment by bartgol** [comment]
> Another even simpler option (which I think is a non-starter because it would require P3 calculations after P3 ends) is to have P3 return the amount of water precipitated in a step rather than the precipitation per second (ie a mass rather than a flux). 

Why would that be a non-starter? We do calculation after the internal proc impl has ended in other places too. All the post-processing kernels do just that. We would have to add a kernel (or add an if inside the P3 postproc kernel) that scales the quantity.

I didn't mention this option b/c I assumed you wanted to preserve a pristine P3 implementation, but if you are willing to change that, then I don't see why we shouldn't.

**Comment by AaronDonahue** [comment]
I think something we want to keep in mind is where we want to rescale the flux and what information we have at hand.  I would advocate for rescaling the flux inside the atmosphere process interface (in this case P3).  If we go with a final step like `precip_total /= num_subcycles` then P3 would need to a) know that this is the last subcycle step and b) how many subcycles to scale by.

Alternatively, if we convert the precip after p3 main to a mass instead of a flux (either in p3_main, or in the interface) then we only need to scale the precip by the global `dt` every time we add it, so `precip_total += precip_local / dt_atm`, which means we just need to pass the `dt_atm` to the atmosphere process and not worry about checking if this is the last subcycle.  IMHO this is a safer approach, if in the future we end up having non-constant `dt_sub` (like if we try a RK type physics timestep) or if someone subcycles has nested subcycling of P3 where `num_subcycles` may mean something different to the driver and to the atmosphere_process_group, we would still be safe.  Thoughts?

**Comment by bartgol** [comment]
We can change the signature of `AtmosphereProcess::run` to be
```
void AtmosphereProcess::run (const int dt_atm, const int dt_proc);
```
where the first is the overall atmosphere timestep, while the second is the dt by which this atm proc is requested to advance. This would give every atm proc an information regarding the overall time step, which they can use for this kind of operations.

From the software point of view, I think the best approaches are (in random order):
- have P3 compute a precip mass rather than a precip rate (other atm procs that need rates can divide by dt)
- have P3 compute a precip mass during subcycling, and divide by dt_atm after the last subcycle.
- have P3 update precip rate at every subcycle with `precip_rate += precip_mass / dt_atm`.

The second is probably the easier to implement right now. The first makes P3 completely agnostic to subcycling. The latter does not require any knowledge about the current subcycling iteration (though it requires to set `precip_rate=0` before the 1st subcycle iter).

All three approaches would require P3 impl to work with precip mass, and let the interface compute the precip rate from that. On the other hand, Peter's idea (which works only for constant subcycling timesteps) would allow to leave P3 impl as is, and simply rescale the quantity at the end.
The former

**Comment by AaronDonahue** [comment]
I would note that we can keep the p3 impl as it is and still do any of these options by just multiplying by `dt_proc/dt_atm`.  So any of the three options above can still be done with minimal changes to P3.

Additionally, I think we would need to set the `precip_rate`, as it is defined in Luca's comment, to 0.0 at the beginning of a new step no matter what approach we use.  Since we will still need to compute the accumulation of something over the subcycles.

**Comment by PeterCaldwell** [comment]
One big-picture issue which I (at least) haven't paid attention to is that we probably want each P3 call to return precip just for the substep it's on because if you substep a bunch of processes together that's what subsequent processes would expect. For instance, if SHOC used precip and precip was accumulated from substep to substep, it would start getting weird answers. Maybe this is a made-up problem since SHOC doesn't use precip, but it still seems odd for a process to return values that aren't local to that substep. I think we handled this in EAMf90 by entwining code around the substep loop which accumulated quantities returned by microphysics. My understanding is that is harder to do in EAMxx because code outside of individual processes is meant to apply to all processes. To partially deal with this, perhaps P3 should return both the substep precip and an accumulated precip variable?

In terms of whether we should accumulate precip mass or precip fluxes - I think it would be least confusing if whatever is accumulated makes physical sense by itself. Accumulated precip mass does that because it is the mass collected over the dt that's passed so far. Luca's option 3, which is sum(substep_flux*dt_local/dt_total) doesn't make sense until you've finished all the substeps (though I guess it is the full dt flux assuming precip in the substeps you haven't run yet are zero... but that's weird too).

**Comment by AaronDonahue** [comment]
Peter brings up an important point about how the fluxes are used.  Precipitation is meant to be used by the surface coupling, so it would be fine for it to always reflect the accumulated precipitation so far.  But other fluxes may be used by other processes and Peter is correct that this could lead to some strange behavior.  I'm not sure how to handle this correctly.  I see three potential cases:
1. the flux is used by exactly one other process.
2. the flux is used by multiple processes
3. the flux is used by surface coupling.
For (3) the solution we have been discussing should work.  for (1) and (2) however we get the weird behavior.  If only (1) is possible we could switch to a paradigm where the process that uses the flux is also responsible for resetting it. 

In terms of what to accumulate.  Again, that is a good point.  If we scale by `dt_atm` every substep it is true that we will, in the end, have the proper value, but the intermediate values won't make any physical sense.  I would vote now that P3 produce precipitation mass which can simply be accumulated, and in the surface coupling interface we convert this to a flux by dividing by `dt`.  That would also mean we wouldn't need to pass dt_atm to p3 or any of the other processes.

**Comment by PeterCaldwell** [comment]
Yeah, I vote for having p3 return precip_mass and have surface coupling and output convert that into a flux by dividing by the full-model timestep. I'm open to other considerations I haven't thought of though.

**Comment by bartgol** [comment]
So p3 will _always_ do `precip_mass += new_mass`, regardless? Namely, P3 will not have to check at what stage of the timestep it is called, right?

**Comment by PeterCaldwell** [comment]
>So p3 will always do precip_mass += new_mass, regardless? Namely, P3 will not have to check at what stage of the timestep it is called, right?

Yeah, that's my vision.

> Surface coupling can take care of emptying the precip mass, I suppose.

Having surface coupling take care of zeroing precip mass seems like creating special cases, which will eventually be hard to unravel. I'd rather loops had a pre-process step where the processes they were going to call could apply some code (like zeroing out precip_mass). But maybe that's too complicated for our current sprint. If so, doing this in surface coupling is fine...

**Comment by bartgol** [comment]
Yeah, I understand your concern. However, we are already doing ad-hoc calculations for several other variables inside the SC class. Not that it makes adding one more "right", but, so far, not much more complicated.

Long term, we could think of marking some fields as "single-step" quantities, which, at the beginning of an atm step, must be reset to a value that is an "identity" for the operation that they undergo. E.g., for accumulated fields, reset to 0, while for fields that are "max" operation (like `f = max(f, some_new_value)`), reset to -infinity. The AD could easily take care of "resetting" these fields at the beginning of the time step.

**Comment by AaronDonahue** [comment]
```
Long term, we could think of marking some fields as "single-step" quantities, which, at the beginning of an atm step, must be reset to a value that is an "identity" for the operation that they undergo. E.g., for accumulated fields, reset to 0, while for fields that are "max" operation (like f = max(f, some_new_value)), reset to -infinity. The AD could easily take care of "resetting" these fields at the beginning of the time step.
```

I like this idea.  I share the same concerns, getting into the habit of having one process create a flux and another reset it could easily lead to annoying bugs.  Especially if we create a new process and forget to have the new one take care of resetting.  Luca's long-term solution seems like a good way to put the responsibility in the AD hands which is a lot safer.

In the meantime I'll implement this plan so we can move on with subcycling.
