### ISSUE TITLE
In Homme prim_driver.cpp, the compute_diagnostics boolean is computed incorrectly.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1757]
It appears that if disable_diagnostics is false, then prim_driver.cpp always sets compute_diagnostics to true, needlessly making expensive `diags.run_diagnostics` calls at every dynamics time step. This explains various performance issues we've seen when diagnostics are turned on, even when statefreq is a large number.

**Comment by mt5555** [comment]
Correct fortran code, for reference:
Diagnostics computed (and then printed) for the first couple of timesteps, and then every statefreq timesteps after that:

```
    ! activate diagnostics periodically for display to stdout and on first 2 timesteps
    compute_diagnostics   = .false.
    if (MODULO(nstep_end,statefreq)==0 .or. (tl%nstep <= tl%nstep0+(nstep_end-tl%nstep) )) then
       compute_diagnostics= .true.
    endif
    if(disable_diagnostics) compute_diagnostics= .false.
```

**Comment by bartgol** [comment]
Uhm, the lines of code are these
```
  bool compute_diagnostics = false;
  if (nstep_end%params.state_frequency==0 || nstep_end==tl.nstep0 ||
      nstep_end>=next_output_step) {
    compute_diagnostics = true;
  }

  if (params.disable_diagnostics) {
    compute_diagnostics = false;
  }
```
This logic was copied from F90, but the latter might have changed since then. Comparing the two, it seems CXX computes diagnostics also for output steps, while F90 doesn't. It also seems that F90 computes diags for the first 2 steps, while CXX only does it for the first step.

When running through EAMxx, we should _not_ have any output. However, I suspect that `nextOutputStep` in `time_mod.F90` being never inited in EAMxx runs causes it to be 0, and therefore `nstep_end>=next_output_step` is always true. Perhaps we should init `nextOutputStep` in `time_mod.F90` to something very large.

Should we move this issue to the upstream?

**Comment by ambrad** [comment]
Closed by E3SM PR https://github.com/E3SM-Project/E3SM/pull/5046
