### ISSUE TITLE
active_gases in SCREAMv1 ICs with pg2: short-term fix

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1782]
Recall that the EAM IC procedure uses only dycore data and so is independent of physics grid configuration. In contrast, the SCREAM IC framework uses some physics data. We are moving toward having only dynamics data, but aren't there yet. After PR #1764 goes in, the active_gases list (excluding h20, which is equivalent to qv) will still need to be read from the IC, but that should be it on the physics side.

The question now is what to do for pg2 for the 1 Sep deadline. I'm considering the following two options, although there may be more, and would like input from others:
1. Put the active_gases data on the dynamics grid in the IC file, regardless of physics grid config. That makes the IC file independent of physics grid config, too, as in EAM. The active_gases fields will then be automatically remapped to the pg2 grid if needed, outside of the radiation interface.
2. Make a separate nc file for just the active_gases that the radiation interface directly reads, similar to how SPA works. In this case, the active_gases data would be on the intended physics grid.

I'm explicitly rejecting:
  3. Modify the IC framework and file format to read data on different grids. IMO, this should be rejected because ultimately we want the IC file to be like the one in EAM, containing only dycore data, so modifying the IC framework and file format would be a waste of time.

Thoughts and preferences?

**Comment by PeterCaldwell** [comment]
Agreed that option 3 is NOT the way to go. I think you should do whichever of option 1 and 2 seems easiest to you. Some unimportant thoughts/questions:

How is option 2 different from the long-term solution we want to implement? Is the long-term solution to read these gases into the AD and option 2 is a hack because it stuffs this info directly into the radiation code? I could see how we might eventually need to read into the AD to allow for prognostic GHGs, but otherwise I think this hack would be fine. If you follow SPA, option 2 might develop a dependency on Jeff's horiz regridding PR. 

Note that option 1 sounds scary at first because it requires extra interpolation which might break conservation. But GHGs are just being read in so we don't need them to be particularly accurate. Maybe nobody else worried about this, but my first thought was "what will this do to BFB restarts!"... the answer is "nothing".

**Comment by ambrad** [comment]
> How is option 2 different from the long-term solution we want to implement?

I haven't looked at EAM's approach, but I think EAM handles radiatively active gases somewhat like prescribed aerosol inputs. In the future, the reworking of SPA would also likely lead to a solution for these trace gases. Here, instead, option 2 means creating a 3D pg2 file for the fields, and the radiation interface would simply read in the values. These data would be available from a v0 ne1024pg2 run. This final point is the main attraction of this approach.

Option 1 is a little clearer. But its big downside is that the IC file for ne1024, for example, will need these fields injected in on the dynamics grid, even though the v0 ne1024pg2 output files will only have the data on pg2.

Thus, Ben will likely have to weigh in.

**Comment by PeterCaldwell** [comment]
Options 1 and 2 both seem reasonable - so long as the gases inputdata are 2d (which I'm pretty sure they are), the ne1024pg2 input file (option 1) won't be too big. And interpolating the existing ne1024pg2 data to ne1024np4 shouldn't be a big deal. 

But agreed that @brhillman should weigh in.

**Comment by brhillman** [comment]
For a short-term solution, I’m not sure it matters much between 1 and 2, but I might have a slight preference for 2. Option 2 is more similar to what EAM does; most trace gases are initialized from surface values that are then extrapolated, while ozone (in the case of using prescribed ozone) is read from a file and interpolated online (see https://github.com/E3SM-Project/scream/issues/1768). In order to do exactly that, we will need Jeff’s simple online remapper. I believe Jim is working on calling the EAM F90 codes that extrapolate the other trace gases from prescribed surface values. But I think a contingency plan of moving initialization of these gases to a separate file is a good short-term strategy, and can be done now, in parallel with those other efforts.

**Comment by ambrad** [comment]
@brhillman thanks. I will implement option 2.

**Comment by PeterCaldwell** [comment]
Good points. It seems like this issue is somewhat redundant with https://github.com/E3SM-Project/scream/issues/1768, but seeks a quicker/temporary fix. We probably shouldn't simultaneously pursue both fixes. @jgfouca - have you made much progress with getting the F90 codes which read gases working? Do you have a sense of how long that effort would take? If the answer isn't less than a day, maybe we should abandon it in favor of one of these quick fixes?

**Comment by jgfouca** [comment]
@PeterCaldwell I have not looked at #1768 . I finished a large assignment for my other project on Monday, so I will have more time to do SCREAM work this week, so hopefully i'll get some of my issues done.

**Comment by brhillman** [comment]
@PeterCaldwell I’m a little confused by your suggestion. We do still want the fix @jgfouca was going to work on, and I do not think this is at odds with the quick fix suggested here. I think a reasonable approach is to impl the quick fix to move initialization of these fields to a separate file, then as Jim impls the EAM init style, we can move fields from init-from-file to init-via-surface-emissions (which, recall, is NOT init-from-file, but init via single value extrapolated in latitude and vertical level). But we do still ultimately need the init-from-file approach for, e.g., prescribed ozone.

**Comment by PeterCaldwell** [comment]
@brhillman - I think we're in agreement. We will implement Andrew's quick fix now to quit blocking progress and Jim's "recycle F90" approach will eventually replace Andrew's quick fix once it's done. I shouldn't have suggested Jim abandon his effort if it takes longer than a day. That was just "if it's not done by Sept 1st it's dead to me" thinking.

One detail I'm not clear on though - EAMf90 must already have a init-from-file methodology to handle ozone and others, right? Is getting that working with EAMxx part of Jim's task or not? Since it is part of the init code, it could be. I suspect we won't want to use it because Jeff's horiz interp will be cleaner. Just asking to make sure we're all on the same page.

**Comment by brhillman** [comment]
From what I can tell, the only thing (at least in our SCREAMv0 cases) that is inited-from-file is ozone. I think what Jim is working on is separate from this; we should retain the ability to init-from-file prescribed ozone, but my vision is that this will, for the time being, use Andrew’s quick fix, and then once Jeff finishes simple horiz remap we will use that to read and remap the same ozone file that EAM/SCREAMv0 uses. We *could* consider just adopting the F90 code to do this, but I think there might be time interp as well which would mean it’s not just an init thing but could be called at runtime.

Related to this, I’m working on the interim IC file for ne1024, and I’ve pulled the gas constituent concentrations into a separate file (remap from ne30 to target grid, then merge with IC file). That gas constituent file alone for ne1024 is 195 GB, which is really slowing down the IC generation. Thus, Jim’s work will be very much appreciated as soon as it’s ready so we can strip that file down to just ozone.

**Comment by PeterCaldwell** [comment]
> That gas constituent file alone for ne1024 is 195 GB, which is really slowing down the IC generation

This is a point that's been bugging me since the start of this git issue. We ended up adding horiz interp to SPA because the size of ne1024 SPA files was gargantuan and reading them in in init took hours. So I'm unsurprising that generating the gas files is also painful. On the other hand, aren't those same 3d ne1024 fields already in the initial condition file? Why wan't it a big deal to read these fields in with the other IC variables but is all of a sudden painful when we read them in on their own?

**Comment by ambrad** [comment]
The issue with SPA is reading the map file.

Here we're just reading 3D fields, like any IC 3D field. Kind of painful to have to read more than necessary but not a huge blocker.

**Comment by brhillman** [comment]
> The issue with SPA is reading the map file.

This is the current issue with SPA, but if I remember correctly we did originally try the strategy of remapping offline, and reading in SPA data on the target grid. This proved intractable, I think partly because we had fields dimensioned (ncol, nlev, nband) for the optical properties, so we decided to instead have one generic SPA input file and do an online remap with a specified map file. I think this is what Peter is referring to.

**Comment by PeterCaldwell** [comment]
Ah yes, that makes perfect sense. We struggled with v0 ne1024 with SPA but not GHGs because v0 uses the trick Jim is working on to avoid reading in ne1024 3d GHGs. I was just having a brain fart.

**Comment by brhillman** [comment]
> Ah yes, that makes perfect sense. We struggled with v0 ne1024 with SPA but not GHGs because v0 uses the trick Jim is working on to avoid reading in ne1024 3d GHGs. I was just having a brain fart.

Right, so I think the thing Jim is working on is really important. Maybe not blocking, but really important.

**Comment by ambrad** [comment]
Agreed that we need a long-term solution. But backing up and just stating the obvious, this issue concerns 7 3D fields that we'd prefer not to have, compared with something like ~15 (~10 tracers + ~5 dynamics) that will always be needed (or, if we end up setting some microphysics fields to 0 in addition to TKE, perhaps ~10 fields). So either short-term solution will increase the input data size by only ~1.5. Option 2, which I'll implement, will increase the size by only ~1.25 since it's on the pg2 grid.

**Comment by PeterCaldwell** [comment]
That makes sense and sounds fine. Sorry for asking a bunch of questions...

**Comment by ambrad** [comment]
Now that Ben told us that he has an ne1024 IC for v1, I'm going to switch to option 1. Then the pg2 config uses the same IC file as the np4 config, and I don't need to introduce a new input file for this short-term fix.

**Comment by ambrad** [comment]
Closing this as I have a working solution in my pg2 branch.
