### ISSUE TITLE
Mass and Energy Conservation in EAMxx

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#1829]
We need to implement a mass and energy conservation checker similar to the one used in EAM.  See https://github.com/E3SM-Project/scream/blob/master/components/eam/src/physics/cam/check_energy.F90#L305

This issue is meant to spur discussion on what the structure of that checker may look like.  We can use the F90 code above as a template for the algorithm we will use to check the mass and energy, which is fairly straightforward.  The args it needs are
1. All of the water species in the run (qv, qc, qr, qi)
2. Any surface fluxes (evaporation, precipitation, etc.)
3. The static energy (which can be derived from the temperature)

Ideally the checker will be designed so that it can be called after every process has updated the model state.  Which includes during subcycling.  We probably don't want the checker to also be called after a group of processes has been called because presumably we've already checked individual processes.

The current vision is to create two field property checks, one for mass and one for energy.  The field property checks would need access to the fields listed above.  They would also need to store persistent records of the current mass and energy, that way there is something to check against.  I.e. we can check that `mass_new = mass_old + mass_flux_at_surface`.  Same for energy.

The bulk of this task is in organizing the field property check, defining the persistent variables and adjusting any of the field property check infrastructure to facilitate calling after a process without having to add it within a process.

A critical task is how to manage surface fluxes.  These are only applied once, so we only need to check them once.  We have some ideas on how to treat that, see comments below.

**Comment by AaronDonahue** [comment]
@bartgol , I'm creating this issue to help @tcclevenger , who has kindly volunteered to take on this task.  I figure we can have a discussion of implementation here.

**Comment by AaronDonahue** [comment]
@tcclevenger , Luca and I chatted about the surface fluxes issue quite a bit.  I looked back over the Slack convo and I think I will copy/paste my final thought on it after our discussion here as a starting point for this discussion:
```
I'm leaning towards having a set of 2d variables in the field manager for vap, liq, and ice flux.  Then I think each process should compute those if needed.  We can have them deep copied to 0.0 in the atm_proc RUN.  It seems to me that would be the most general and take the logic of what needs to be done outside of the AD and EAMxx and put it squarely in the responsibility of the process itself.  I think for example if we had some macrophysics scheme that scales evaporation, or some random process that uses an external source or sink for mass that is not microphysics or macrophysics.





[11:57](https://acmeclimate.slack.com/archives/DD7JB7RGV/p1658429825544699)
When it comes to energy conservation I think we need a heat flux too
[11:57](https://acmeclimate.slack.com/archives/DD7JB7RGV/p1658429846748749)
So I could see some process maybe having a heat dissipation not related to evap or precip...
```

**Comment by AaronDonahue** [comment]
I think the thrust of this idea is that we need someway to pass surface fluxes to the checker and to indicate that we actually want to use them.  In EAM the energy checker has to be explicitly called, and thus it is easy to pass args.  In the case of surface fluxes, if there are none to consider than you just pass 0.0.

We want to avoid forcing the user to have to explicitly call the checker and pass those args, so this was in my view a simple solution.  Have a set of surface flux 2D variables in the field manager that are always set to 0.0 before a process is called.  Then, if a process needs to update these they can grab it and change it.  Inside the checker we will always access these fields and if they are zero, anything we do with them will have no impact if they are zero.

**Comment by AaronDonahue** [comment]
This approach also avoids special cases, like relying on `precip_liq_flux` in one case, but what if there is a different liquid flux from a different process, do we have to add that new field to the mass checker?  What if we don't run with that new process? etc.  Having a generic flux field abstracts these particulars out.

**Comment by oksanaguba** [comment]
i probably not fully follow, but what is the problem with `We want to avoid forcing the user to have to explicitly call the checker and pass those args,` ? Whoever 'designs' the call to a physics package should be responsible for properly calling checks, since they will know which fluxes the package actually used (applied). Is it that now checks will be called "automatically", without a user input, so, checks themselves need to know when to use fluxes for a package and when not too? It seems too complicated compared to making this user's responsibility. By user I assume we mean a person who will introduce a package call to the interface.

**Comment by PeterCaldwell** [comment]
I had the same reaction as Oksana. It seems overly complicated to automatically grab all variables.

**Comment by AaronDonahue** [comment]
@oksanaguba , yes, this is where we run into the differences between the EAMxx and EAM infrastructure.  There are a few problems with setting things up the way they are in `physpkg` in EAM:
1. The AD doesn't have `physpkg` in the same way.  Instead, the AD gathers the processes to be run in a group and sequentially calls their `run_impl` in order.  So at the AD level there isn't the same ability to hard-code a checker dependent on the process that was just called.  Instead, each process needs to take care of that.
2. We could have the `run_impl` in the process call the checker instead, which would be as close to EAM as we can do, but we have the issue with the persistent record of the last mass and energy in the system.  The closest thing we have to a PBUF, which is what check_energy does, is the field manager.  Or we would need to have the user set the mass at the beginning of the run_impl and then check it at the end.

**Comment by AaronDonahue** [comment]
We could also just have mass and energy be in the field manager, so if the checker is called it will grab those, check they haven't changed (given the fluxes) and then update the mass and energy.  That way we have persistent mass and energy in the system.

**Comment by bartgol** [comment]
Would it be bad to compute the mass/energy at init time, and require all checks to cmp against that initial value?

**Comment by AaronDonahue** [comment]
we need to update it though, since surface fluxes add/remove mass.

**Comment by PeterCaldwell** [comment]
You could also have the interface layer of each process call a function which checks dwater and denergy from the beginning to the end of each process.

**Comment by AaronDonahue** [comment]
> 

right, that is essentially what this field checker approach would be.  The field property checker approach just uses an infrastructure we already have.  But I think the implementation would be largely the same.

**Comment by AaronDonahue** [comment]
Recall that mass and energy still need to know what fluxes, if any to use.  So we would have to define those somewhere by process.  The original idea above is to define FM variables that record the flux, if a process updates those they are used, if they are untouched then we don't use them.  Then if a process changes vapor, water, ice, etc at the surface then the process sets those flux values.

**Comment by PeterCaldwell** [comment]
It seems like mass conservation doesn't care what fluxes it gets passed - we should just always pass it the total sum of all surface fluxes. Likewise energy checking just needs to total energy flux through the boundaries, which is a bit trickier because different water species have different condensational heating coefficients for vapor, liquid, and ice. Can we just pass the sum of all 3d water tendencies and the sum of all 2d surface fluxes to the water checker and similar quantities for moist static energy to the energy checker?

Maybe I don't understand what you're imagining, but it sounds to me like you're imagining a code which initializes to zero all possible fluxes any process in the model could create (i.e. precip_surf_liq, precip_surf_ice, surf_evap, surf_sens_flux, etc), then overwrites the ones used by the particular process with nonzero values. This seems overly complicated and brittle (though maybe my approach puts too much on the process developer's shoulders).

**Comment by AaronDonahue** [comment]
Oh, no... Sorry for the confusion.  I was envisioning exactly what you are suggesting.  We would have `water_flux`, `ice_flux` and `heat_flux`.  Then each process could set those.  We wouldn't care about what format the flux came in.

**Comment by AaronDonahue** [comment]
Looking at the signature of args for the EAM implementation it looks like 4 are needed:
```
flx_vap, flx_cnd, flx_ice, flx_sen
```

**Comment by AaronDonahue** [comment]
As for the 3D fields, we need to distinguish between ice and water for energy calculations, because these use a different latent heat.

**Comment by AaronDonahue** [comment]
So for example, in P3 we would have `water_flux = -precip_liq_flux/dt` and `ice_flux = -precip_ice_flux/dt`.  In SHOC we would have `vap_flux = surf_evap`

**Comment by PeterCaldwell** [comment]
Ahhh. those 4 arguments is exactly what I was hoping for. Sounds great! Sorry for misunderstanding your plan. And I hope we don't use flx_cnd to refer to liquid water flux <insert horror emoji>

**Comment by bartgol** [comment]
The `PropertyCheck` class is meant to handle things somewhat agnostically. If we are ok putting _some_ responsibility on the developers of new processes, then we could just write a function, EAM style. Something like
```
void check_mass (Field* q1, ..., Field* qN, Field* flux_1,..., Field* flux_N) {
  Real mass = 0;
  if (flux_1!=nullptr) {
    // add flux_1
  }
  // Same for other fluxes
  if (q1!=nullptr) {
    // add q1
  }
  // same for other qi's
  
  // Note the trick: the initialization happens only the 1st time this fcn is called!
  // Subsequent calls basically skip this line, while leaving the var present and unchanged
  static Real old_mass = mass;
  EKAT_REQUIRE_MSG (std::abs(mass-old_mass) < tol,
    "Error! Mass conservation broken! Here are some details: ...");
  old_mass = mass;
}
```

**Comment by tcclevenger** [comment]
Am I correct in assuming that sums are within columns? Or are they over columns as well?

**Comment by AaronDonahue** [comment]
Within columns, yes.

**Comment by bartgol** [comment]
From the convo above, it appeared to me that the checks were global. That said, it's true that physics is column-local, so we can perform the check locally, but that means no mass/energy check for dyn.

**Comment by oksanaguba** [comment]
I believe what you need now is column-wise checks for physics. Dynamics is not an issue at the moment (dycore prints its own mass diagnostics and it won't conserve energy anyway). There will be need to globally integrate energy later.

I could not follow the conversation above. Is it possible to create some sort of a code chart with calls to energy checks and whatever is around them? If not here, then maybe on confluence?

Also, there is a complication in e3sm that the physics time step starts "in the middle" of the time step as seen by the code -- it starts by tphys BC, not by tphys AC. How is it done in scream?

**Comment by tcclevenger** [comment]
> So for example, in P3 we would have `water_flux = -precip_liq_flux/dt` and `ice_flux = -precip_ice_flux/dt`. In SHOC we would have `vap_flux = surf_evap`

@AaronDonahue Where are you getting these calculations? For instance, I see in P3 AD interface post processing
```
precip_ice_surf_mass(icol) += precip_ice_surf_flux(icol) * PC::RHO_H2O * m_dt;
```

**Comment by AaronDonahue** [comment]
Hi @tcclevenger , yes.  Mass conservation checks have to account for the variables that represent mass entering or leaving the system.  In SHOC there is extra mass gained by surf_evap.  So the total water mass after shoc should equal the mass before shoc + the mass from surf_evap.  For P3 mass leaves the system in the form of precip_liq/ice_surf.  So again the mass after P3 should equal the mass before P3 - the precipitation.

For precip we have to be careful since the precipitation is set to a total mass, not a flux.  So in the mass conservation calculation, if we are thinking of a general water mass flux then precip needs to be converted to a flux by dividing by `dt`.  This idea of thinking in terms of a general flux comes from the approach in EAM - see https://github.com/E3SM-Project/scream/blob/master/components/eam/src/physics/cam/check_energy.F90#L320

We probably want to do the same, i.e. let each process define a generic flux for each water species, rather than have some check to see if P3 just happened or SHOC just happened.

**Comment by tcclevenger** [comment]
I'm able to focus solely here now. I have a lot of questions, so maybe it's best to try and group them together and ask one at a time (since they may start answering each other). Let's start with energy. The way I understand it:

**Goal**: Creating a `class EnergyConservationCheck : public PropertyCheck` with `check()` function modeled after `check_energy_chng()` in `check_energy.F90`. 
- This property check is added by any process that updates fields used in the `total_energy` calculation: `u,v,T,q,pdel,phis,ps`
- We need to compute an`expected_total_energy` quantity
   - `old_total_energy + energy_tendancy*dt`
   - `energy_tenancy` calculation needs new fields `water_flux, heat_flux, vapor_flux, ice_flux`, defined by the process adding the PropertyCheck
- Throw error if `total_energy - expected_total_energy < tol` (should be a relative error)
   
Questions: 
1. For `water_flux, heat_flux, vapor_flux, ice_flux`, where do I find these calculations?
    - If a process only updates a subset, is it good enough to set others to 0 (and same with total energy calculation)?
2. Will almost every process call this? I think e.g. `T_mid` is used in the `total_energy` calculation and `T_mid` is an `Updated` field in shoc,p3,rrtmgp,dynamics.
3. Is it enough for each process to say "This was my `total_energy` last time around, lets compute new `expected_total_energy`" without considering that `total_energy` will have changed from other processes?

Feel free to only respond to a subset of these questions or to correct misconceptions about the goal. If I'm way off, maybe it would be helpful to have a quick chat instead of messaging here.

**Comment by bartgol** [comment]
I think this check should be created from the AD, which has access to all the required fields. Then, the AD should set the check in the atm process, so that it gets run (along with any other check created by the atm proc) automatically. As for other checks, users can disable/enable checks via input/xml file.

In this setting, the first time the check is run, it will simply store the value of energy, without any check (we could do this in the AD, at the end of the init sequence). From the next time on, a valid old_energy value exists, so the check can indeed compare.

Note: currently, we don't set a pre-built PropertyCheck in an AtmosphereProcess from outside, but it can be done. The only thing to change would be to make the `add_[pre|post]condition_check` methods virtual, so that AtmosphereProcessGroup can set them on all the inner processes, rather than on itself. I have a branch where I started this. I can revive it.

**Comment by tcclevenger** [comment]
Yeah, just point me to that branch.

Ok, so then from the AD level, if a field doesn't exist then pass a null_ptr to the constructor and ignore that part of the computation? Assuming the constructor takes in a list of `Field*` as input.

**Comment by tcclevenger** [comment]
Is this the commit? https://github.com/E3SM-Project/scream/commit/159709e37277a2732fc13e8abad04790fcfd4538

**Comment by bartgol** [comment]
Yeah, that was it, but looking at it, it seems complicated and not too clear. Beisdes, #1911 is also changing a bit condition checks, allowing to make add_xyz_check virtual (right now they can't be virtual b/c they are templated functions).

**Comment by tcclevenger** [comment]
Them being virtual-ized will make things much easier. I'll base off that branch.

**Comment by bartgol** [comment]
You can have EnergyConservationCheck store pointers to total/flux energy, so that the method can remain const, while the pointees (not the pointers) are updated.

I'm not sure I follow option 2.

**Comment by tcclevenger** [comment]
Option 2 would be to have a generic property check which only checked if 2 fields were equal. Then we hand it total energy and flux energy. But now that I think about it more, we need to check total energy vs. expected total energy, which is a bit more confusing to have a FM variable "expected total energy". I'll work around the const-ness issue in option 1 for now.

**Comment by tcclevenger** [comment]
Now I'm on to the fluxes. In [Line 375](https://github.com/E3SM-Project/scream/blob/80956ec0a53c43b490eacdf9eecbfa4a7699232e/components/eam/src/physics/cam/check_energy.F90#L375)  of check_energy.F90, we have the flux computation
```
te_tnd(i) = flx_vap(i)*(latvap+latice) - (flx_cnd(i) - flx_ice(i))*1000._r8*latice + flx_sen(i)
```
compared to the total enery calculation in [Line 1257](https://github.com/E3SM-Project/scream/blob/master/components/eam/src/physics/cam/check_energy.F90#L1251)
```
te = se + ke + (latvap+latice)*wv + latice*( wl + wr )
```
where `se,ke,wv,wl,wr` are combinations of various fields.

My questions
1. Are these linked `(se+ke)->flux_sen`, `wv->flx_vap`, and `(wl+wr)->flx_cnd-flx_ice`, e.g., if a certain process updates only `wv` (equiv to it updating `qv`) then it should also only define `flux_vap`?
2. How do I find the equiv. fields for each flux? @AaronDonahue you posted earlier P3: `water_flux = -precip_liq_flux/dt`, `ice_flux = -precip_ice_flux/dt`. SHOC: `vap_flux = surf_evap`. Is this exhaustive? It looks like shoc updates `se+ke`, `wv`, `and wl`, so should it need to define all 4?

**Comment by bartgol** [comment]
From your first point I'm inferring you want to detect which parts of the energy balance eq each process will update. I'm guessing you want to find a way to allow each atm proc to create the energy check, passing only the parts it has. I think we should not have processes add the energy check, but rather build it on the AD side (where all fields are available), then "append it" manually to the existing prop checks of each atm proc whose type is "Physics" (since we cannot check dyn locally on each col b/c of halo exchanges).

**Comment by AaronDonahue** [comment]
@tcclevenger , in terms of a process defining all 4 fluxes.  I guess this is an implementation question.  There is no doubt that some processes won't have non-zero changes to all of the fluxes.  But if you want to have all processes start by zeroing these out and then only updating those that are relevant that would probably be okay.  

As for where to track down the fluxes related to energy.  I would have to look through the EAM code.  Processes like SHOC and P3 do define these, I believe through PBUF, in their respective interfaces.  We would need to update our own process interfaces to reflect the same calculations.

**Comment by tcclevenger** [comment]
@bartgol What I am doing is, the AD creates a `EnergyConservationCheck` object (it will include mass part later) with all the fields it could possibly need, then the `atm_process_group` loops through and adds that energy check to an atm process if that atm process will have changed any field in the energy calculation.

For example, shoc has `T_mid`, `horiz_winds`, `qv`, and `qc` as `Updated` fields, therefore the `se`, `ke`, `wv`, and `wl` part of total energy might have changed after running shoc, so the energy check is added.
But cld_fraction has none of these fields (nor does it have `qc` which affects `wr`), so it does not add the check.

But this means that each time the check is run, energy is calculated based on all non-null fields it has (even from other processes). So if the checker was given `qr` in the AD level, then when the postprocess is run for shoc, it will still use this field although shoc does not update it. I'm assuming this is fine. Or should the `check()` call be custom to the process that calls it? I.e., shoc calls it and says "don't include fields I don't update, even if they exist in the checker because P3 added it".

**Comment by bartgol** [comment]
Ah, I see. Well, I guess it depends on how _complex_ the check is. If it boils down to summing/multiplying a handful of fields, then I think we can always run the full check. If it's more complicated, then we can think of how to run only _some_ parts of it.

**Comment by tcclevenger** [comment]
The check should be cheap so I plan to just run the full check,

**Comment by tcclevenger** [comment]
@AaronDonahue Ok great, I'll hunt them down!

**Comment by bartgol** [comment]
At some point we can/should also add timers in the checks, to have a more quantitative feeling of how much all our tests cost.

**Comment by tcclevenger** [comment]
I think I am defining theboundary flux variables incorrectly. 

Restricting my view right now to microphysics, looking at the call to the checker at https://github.com/E3SM-Project/scream/blob/master/components/eam/src/physics/cam/physpkg.F90#L2664. There they set `flx_cnd = prec_str` and `flx_ice = snow_str` (both `pbuf` variables) where in `micro_p3_interface.F90`
```
! taken directly from p3_main output
prec_str = precip_liq_surf + precip_ice_surf 
snow_str = precip_ice_surf

```
The other fluxes are 0.

This seems straightforward, and the `pbuf` vars seem to directly correspond to the scream vars, but I'm getting relative SCREAM errs of  `~1e-4` where EAM gets `~1e-7`. I looked at the max value of total energy over columns and both scream and eam are `~2.8e9` and looked at the max change in energy (energy before p3 ran - energy after) and they are similar too. So I think my energy calculation is correct, which would leave the fluxes.

I'm testing `SMS_D.ne4pg2_ne4pg2.F2010-SCREAM-HR` vs. `SMS_D_Ln9.ne4_ne4.F2010-SCREAMv1-noAero`. Are these similar at all?

@AaronDonahue you had suggested using `-precip_liq_surf/dt` but I think the units would not line up, and the sign is definitely different to eam.

This issue is difficult to write out, so let me know what is unclear.
