### ISSUE TITLE
Post-condition positivity check sets fields to eps

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1833]
I'm investigating a few different issues in SCREAMv1 that are unrelated in terms of code but related in terms of clues. In the process I've stumbled upon something I believe we definitely do not want.

The dynamics sets a repairable post-condition on the tracers using the positivity checker. That checker then makes every value equal to eps (~2.22e-16) that was originally <= eps. Thus, fields that normally can be and often are 0 in large regions of the earth (true of many of the microphysics fields) at any given time end up being >= eps after every dynamics call.

My guess is this influences climate a little and probably water conservation over time.

Assuming everyone agrees this is a problem, the positivity checker should be replaced by a nonnegativity checker. IMO, a positivity checker that hardcodes eps as the lower bound is easily misused and so should not be available. The domain expert should be the one to set lower bounds other than 0.

**Comment by bartgol** [comment]
Yeah, this seems wrong. We should replace FieldPositivityCheck with a FieldLowerBoundCheck, with lb=0.

If a field positivity check (i.e., F > 0, rather than F>=0) is still desirable, we could change the impl of `FieldWithinBounds`, to allow both `LB<=F<=UB` as well as `LB<F<UB`, and impl FieldPositivityCheck as a Field w/in bounds with strict cmp. Otherwise, we can purge FieldPositivityCheck altogether. I suspect we can do away with that class. It doesn't save that much code compared to a FieldLowerBoundCheck with lb=0 anyways...

**Comment by PeterCaldwell** [comment]
>I think we can simply remove FieldPositivityCheck (it doesn't save that much code compared to a FieldLowerBoundCheck with lb=0 anyways...), replaced by FieldLowerBoundCheck where used, and keep our impl unchanged everywhere else.

Yeah, I agree with this. As further support, I would argue that insisting on x>0 rather than x>=0 doesn't really make sense in finite-precision arithmetic. Users should be forced to say how much greater than 0 they want if they want something greater than 0.
