### ISSUE TITLE
SCREAM_NUM_VERTICAL_LEV should be set correctly based on compset

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#1848]
Both SCREAM_NUM_VERTICAL_LEV and SCREAM_NUM_TRACERS should be set automatically based on compset. Right now the user has to run
```
./xmlchange SCREAM_CMAKE_OPTIONS="SCREAM_NUM_VERTICAL_LEV 128"
```
for other than the default of 72 in scream/cime_config/config_component.xml.

**Comment by AaronDonahue** [comment]
@brhillman

**Comment by bartgol** [comment]
In our XML file we use hgrid to specify input files, which are intrinsically linked to vert resolution. So perhaps, rather than make it compset-dependent, we should ping ATM_GRID in `buildlib` to automatically set `SCREAM_NUM_VERTICAL_LEV` based on horiz grid. If user already set the param via xmlchange, then honor it (to allow running with an IC file with a different number of levels but same horiz res).
