### ISSUE TITLE
'ninja' directory in 'externals' is probably spurious

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/scream#2030]
Looks like the `ninja` directory here: https://github.com/E3SM-Project/scream/tree/master/externals is not meant to be there. Right?

**Comment by jgfouca** [comment]
@ambrad , I added ninja to E3SM a few years ago during the Cmake-ification of the E3SM build system (it was not added on the SCREAM side). I thought folks may be interested in trying it but I had issues getting the backend to work due to CMake bugs, so it's not officially supported. It possible that CMake bugs will get fixed and it will work someday, in which case ninja should offer a faster build than Makefiles. This is my longwinded way of saying that we aren't using ninja now but it's possible we will in the future. If you still want me to remove it, I am happy to do so since it would not be hard to re-add.

**Comment by ambrad** [comment]
The files in that directory show as binary, and catting them indeed shows they are not text. Are those files meant to be there?

**Comment by jgfouca** [comment]
@ambrad , yes. I had to use a special version of ninja for CMake compatibility, so it was not reasonable to expect users to have this version on their machine. Also, ninja must be built and I didn't want to have to build it every time we made a case, so I added some binaries.

**Comment by ambrad** [comment]
I mostly see. I don't understand how these binary files can work on all the machines we run on, but as long as you mean for them to be there, it's fine.

**Comment by jgfouca** [comment]
@ambrad , yeah, binary compatibility of these files was a bridge I never crossed.
