### ISSUE TITLE
SCREAM repo should run some subset of E3SM tests to keep BFB compatibility

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/scream#2161]
Our merge of SCREAM upstream to E3SM has revealed some DIFFs in integration tests between the SCREAM and E3SM repo. We have previously run into diffs in atmosphere tests, but this most recent merge has revealed some diffs in coupled tests as well, even when F-cases are BFB. I think this suggests that, if we are going to continue to develop downstream in our SCREAM fork (which I think we do in order to remain agile), then we might think about expanding our regression tests to include some E3SM integration tests (maybe just a few to give us our best bang-for-buck test coverage). I'm thinking maybe this would mean an additional baseline compare:

Compare scream master <-> scream baselines
Compare scream master <-> e3sm baselines

Help and input wanted!

**Comment by ambrad** [comment]
My suggestions:
1. Run on Chrysalis so we have baselines, if it's OK with @rljacob.
2. Run homme_integration plus a judicious subset of e3sm_integration.

Attn also: @jgfouca

**Comment by rljacob** [comment]
Would these tests run at the AT cadence (once per PR; possibly many times a day)?

**Comment by ambrad** [comment]
@rljacob and others, I recommend _not_ doing this in the AT. A nightly is the appropriate place for this.

**Comment by rljacob** [comment]
anvil is kind of underused now so maybe run them there.

**Comment by jgfouca** [comment]
@brhillman , @ambrad , I am happy to set this up but we will need to clarify a few things.

> Compare scream master <-> scream baselines

This should be trivial since it's basically the same thing that we are doing everywhere, just with a different test suite. We would just need some protocol of what to do when DIFFs come up. With SCREAM tests, we usually just bless and move on. In this case, a bless would imply knowingly diverging from E3SM in terms of BFBness. Does not mean we never approve a PR that causes a DIFF and so would revert the responsible PR? Or do we just make sure to understand DIFFs as they come up and therefore can be more comfortable approving non BFB scream downstream merges into E3SM?

> Compare scream master <-> e3sm baselines

This is much trickier since it involves two different repos and therefore two moving targets. If e3sm gets a non-bfb PR, scream will DIFF against e3sm baselines until we do an upstream merge. Do we just expedite an upstream merge when this happens? What happens if we want a non-BFB change in SCREAM? Do we then do a downstream merge to E3SM?

**Comment by whannah1** [comment]
@jgfouca Can we avoid this complication of E3SM baselines by renaming the tests with a meaningless test mod? Or be sure that the number of time steps is slightly different for the tests run from the SCREAM repo?

**Comment by jgfouca** [comment]
@whannah1 , what you are describing is basically approach 1 with extra steps (maintaining our own baselines for this effort). If I understood @brhillman , what we want to do is run E3SM test cases using the SCREAM repo and making sure we stay BFB (or at least notice when we are not BFB). The question is if we want to use baselines created and maintained by E3SM or maintain our own baselines for this. If we want to share baselines, we will really have to stay on top of the upstream/downstream merges.

**Comment by jgfouca** [comment]
@brhillman , can you look at my last two comments and chime in? I need to understand what exactly the team wants to do and we should have protocols for when things DIFF.

**Comment by jgfouca** [comment]
Obsolete now that it's the same repo.
