### ISSUE TITLE
Write output on 1st time step to make # of samples/day constant for all days.

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#2166]
Currently if we ask for 6 hr output, the first output time will be 6 UTC and the name of the first output file will include 6 UTC in the timestep. This is annoying. It would be better and more standard if all output streams write their first output in timestep 0 in order to have file names start on daily boundaries and to have {0 UTC, 6 UTC, 12 UTC, 18 UTC} in that first day’s file instead of {6 UTC, 12 UTC, 18 UTC, 0 UTC on next day} in that first file. Note that ELM and maybe EAMf90 already do this. 

I think we’d also need to make sure ave, max, and min use the beginning rather than end of the time  interval as its timestamp in the filename. I’m not sure if this is already done.

Tagging @paullric because he's the one most excited about this. I still don't really understand why this is a big deal.

**Comment by bartgol** [comment]
Writing output at t=0 only makes sense for instant output though, so avg output should continue to output nothing at t=0, right?

As for the filename, the output manager gets the timestamp to put in the filename when the file is created, which usually is at the first write step. We can have the OM create the output file right away at init time, and again as soon as one is closed. This may cause the simulation to create an empty output file at the end (created as soon as the last "real" output file was closed), but I suppose that's not too bad.

**Comment by bartgol** [comment]
Wait, do you actually _want_ output to happen at t=0? Or is it just a matter of filenames?

**Comment by PeterCaldwell** [comment]
I'll let Paul answer that... and slack him so he does.

**Comment by paullric** [comment]
If I am tracking storms at 6hr frequency, I will be using multiple variables at 00Z, 06Z, 12Z and 18Z.  Using the naming conventions as they are currently implemented, it is difficult to determine which files actually contain data at these time slices.  For example, daily output would be ..-00000, 6-hr output in daily files would be ..-21600, 15-min output in daily files would be ..-00900, 15-min output in 6-hr files would be -00900, -22500, -44100, -65700.  On the other hand, if t=0 is included in all the output files then regardless of the output frequency or number of outputs per file, I would be simply be looking for files with timestamps -00000, -21600, -43200, -64800.

Consequently, I would propose including t=0 in the output (if instantaneous).  If data is averaged I'd like to include an array of zeros at timestep t=0 (this should be negligible in size because of compression).

**Comment by paullric** [comment]
Here is an example of a "nicely behaved" archive from E3SMv2 on Cori:  `/global/cfs/cdirs/e3smdata/simulations/20210104.maint-1.0-A_WCYCL20TRS_CMIP6_LRtunedHR.ne30_oECv3_ICG.cori-knl.unc11/archive/atm/hist`

**Comment by paullric** [comment]
That recipe sounds good to me.

I asked around to see if I could figure out what was going on at t=0 and got the following response:  "If I recall correctly, output at t=0 is actually output at the end of the first physics call (ie 30 min)."  So in E3SMv2 when a variable was "averaged" at t=0 it would actually output only the results of physics applied to the initialization data.  There are some reasons why this would be desirable (e.g., if computing a climatology this introduces fewer errors than if the field was all zeros), but it's also somewhat misleading (since it's not an actual average).  Any opinions on this?

**Comment by bartgol** [comment]
I don't mind outputing IC data even in the avg_type=avg case. However, my biggest concern is: what do we do if one of the output field is not a state, but, say, some quantity computed in a parametrization? As I said, we can either be crude, and write 0 always at t=0, or we can use option b above, that is: if a field has been initialized (either straight from IC file, or as a result of a parametrization initialization sequence), write the actual values, otherwise write zeros.

**Comment by paullric** [comment]
Yes, I think that's good reason to prefer option b.  This is what E3SMv2 does, so it is also consistent in that sense.

**Comment by PeterCaldwell** [comment]
I like option b - knowing what data was read in by the model might be useful for tracking down bugs or making sure you're using the IC you thought you were using. Basically, it doesn't cost more to provide more info, so we might as well. 

I'm kind of horrified by the thought that our clim averaging is randomly including zeroes in the first month though. I had never heard of this before. I wonder if this explains a bunch of the transient behavior we explain as "spinup". I don't think there's anything we can/should do about my horror here. We should make sure to emphasize this behavior in our imaginary documentation and include it in code comments to the extent we can. I'll ask around to see if other eval people know about this.
