### ISSUE TITLE
Inconsistency between wet MMR/dry MMR conversion functions and AD assumptions?

### ISSUE THREAD

**Issue by quantheory** [E3SM-Project/scream#2169]
Adding another issue, with appreciation for @mt5555 and @oksanaguba for explaining what's going on here.

For a level pseudodensity $\Delta \widetilde{p}$, dry pseudodensity $\Delta \widetilde{p}_d$, and (wet) water vapor mixing ratio $q_v$,

$$ \Delta \widetilde{p} = \frac{\Delta \widetilde{p}_d}{1 - q_v} $$

Whenever an atmospheric process changes $q_v$, we have four options:
1) Update $\Delta \widetilde{p}$ while keeping $\Delta \widetilde{p}_d$ constant; this is effectively asserting that the process is not changing the mass of dry air in the grid cell. This is valid under a "Lagrangian" view of things where the pressure levels are allowed to shift around a bit. (Or in the case of P3, for instance, this would be consistent because the grid is basically treated as Eulerian in $z$ coordinates, and the dry mass in each grid cell is never changed by P3.)
2) Update $\Delta \widetilde{p}_d$ while keeping constant $\Delta \widetilde{p}$. This would potentially be correct for a model with an "Eulerian" grid using pressure coordinates such that the "wet" mass in each grid cell has to be constant.
3) Do something more complicated while updating both.
4) Update neither, introducing an inconsistency such that the equation above does not hold. In this case there are now two different ways of calculating the (wet or dry) mass in each grid cell, and those two methods give different answers.

Since nothing is ever easy, CAM and EAM take option 4. When using wet mixing ratios to calculate the total mass of water in a column, we therefore have to choose whether to multiply the mixing ratios by $\Delta \widetilde{p}$ or $\Delta \widetilde{p}_d/(1 - q_v)$. The "obvious", simpler choice is the former, so that's what Oksana has been using (and I'm assuming that any other conservation checks in the code do the same).

Now as an example, consider what's done by the microphysics in P3, ignoring sedimentation. (I think this problem affects the sedimentation and SHOC too, but this is the simplest example because there's no vertical transport.) The microphysical processes in P3 essentially conserve whatever they think $\Delta \widetilde{p} (q_v + q_c + q_r + q_i)$ is in each grid cell. P3 is intended to accept dry mixing ratios and dry mass, but if you input wet mixing ratios and wet mass instead, it will happily conserve that as well. The process rates will be a bit wrong if wet values are input, but no conservation laws will be broken. I believe this is why Oksana has found that P3 does successfully conserve mass if given "wet" inputs.

In a world where all our variables were consistent with each other, this would also work if P3 was given dry quantities; water mass is water mass, and it should be conserved regardless of whether you use wet or dry "units" to describe them. However, the [two](https://github.com/E3SM-Project/scream/blob/f90b4e036706f1a7fbd6a67080771862d5f79074/components/eamxx/src/share/util/scream_common_physics_functions_impl.hpp#L253) [routines](https://github.com/E3SM-Project/scream/blob/f90b4e036706f1a7fbd6a67080771862d5f79074/components/eamxx/src/share/util/scream_common_physics_functions_impl.hpp#L276) that convert between wet and dry MMR currently use $q_v$ to do the conversion. As a result, when P3 is run using "dry" quantities, and then the result is converted back to "wet" units, the quantity it conserves (expressed in wet units) is $(\Delta \widetilde{p}_d / (1 - q_v)) (q_v + q_c + q_r + q_i)$, not $\Delta \widetilde{p} (q_v + q_c + q_r + q_i)$. These two quantities should be the same, but due to the inconsistency noted above they are not, so we get a conservation violation.

As far as fixes go, I think that the best short-term fix is to change `calculate_wetmmr_from_drymmr` and `calculate_drymmr_from_wetmmr` to use `pseudo_density` and `pseudo_density_dry` to do the conversion rather than using `qv`. [This is how Fortran EAM does it.](https://github.com/E3SM-Project/E3SM/blob/1ceacbc87a183a532bfbe7c64e117e4f45b29530/components/eam/src/physics/cam/physics_types.F90#L1491-L1547) An equivalent "hack" would be to store the value of `qv` used to convert quantities to dry mixing ratios before P3, and use the same value to convert them back at the end (rather than using the new `qv` that has been updated by P3). (I guess this could also be needed for SHOC?)

Either way, it's kind of cruddy that the code works this way in the first place, and I gather that it has caused problems in the past. We shouldn't really be allowing these variables to become inconsistent with each other like this, if we can help it.

**Comment by mt5555** [comment]
Nice description.  a little more info:   This is baked into the CAM design (used by EAM and EAMxx).  Total cell mass (pdel) and pressure is held fixed for all parameterizations, and only updated at the end of the physics.   Individual parameterizations only change the q's and T.   PHI (layer height)  is recomputed from the latest T and qv after each parameterization.

**Comment by bartgol** [comment]
If EAM is doing `qwet=qdry*(dpdry/dpwet)`, I think we should do the same. There's no advantage of the "storing qv" approach vs what EAM does.

I will lso note that the current wed-dry conversion is a bit involved, since we try to convert all non-qv tracers first (to avoid changing qv mid-process) and qv/tke last. If we use dpwet/dpdry as a factor, it becomes simpler, and we can maybe expose a bit more ||ism, ||izing over tracers as well.

**Comment by PeterCaldwell** [comment]
Thanks for the nice description, Sean! Some big-picture thoughts:

1. Recall that we're still using hydrostatic pressure in the physics schemes even though the dycore is using the full NH pressure. The above discussion about choosing which pdel to conserve is probably entwined with the bigger question of how to handle dp in physics overall. That's not to say we shouldn't fix this problem now... but we should probably do the easiest thing since we'll have to revisit the whole dp issue soon anyways. 
2. Like Sean said above, P3 is intrinsically formulated in terms of dry mixing ratio but the difference between wet and dry is so small that climate wouldn't change much if we just used wet mixing ratio everywhere. My feeling is that we shouldn't use wet mmr where we know dry was intended because someone will come along in the future and become hopelessly confused (though I suppose one could argue that we've already gotten ourselves hopelessly confused here!). Also, it's hard to say a priori that wet vs dry won't make a difference in something someone cares about. I could imagine someone figuring out that one group's version of P3 gives different answers than ours and spending years figuring out that it was just that we're using wet instead of dry mixing ratio. In particular, dry mixing ratio will be systematically larger than wet mixing ratio, which will lead to a systematic rather than zero-mean perturbation to the results. I'd be happy to have P3 use wet mixing ratios as a short-term solution while we figure out the larger NH pressure though. And I'm happy for SHOC to always use wet mixing ratio (since it can be equally-well formulated for dry or wet mixing ratios).

**Comment by PeterCaldwell** [comment]
>I think that the best short-term fix is to change calculate_wetmmr_from_drymmr and calculate_drymmr_from_wetmmr to use pseudo_density and pseudo_density_dry to do the conversion rather than using qv

Does using pseudo_density avoid inconsistency just because we're too lazy to recalculate it after qv changes? If so, it's just like saving a copy of qv from before our calculations, but wrapped in an additional level of obfustication.

**Comment by quantheory** [comment]
> > I think that the best short-term fix is to change calculate_wetmmr_from_drymmr and calculate_drymmr_from_wetmmr to use pseudo_density and pseudo_density_dry to do the conversion rather than using qv
> 
> Does using pseudo_density avoid inconsistency just because we're too lazy to recalculate it after qv changes? If so, it's just like saving a copy of qv from before our calculations, but wrapped in an additional level of obfustication.

So first I would say that the `pseudo_density` fix is more future-proof than saving `qv`; it is correct whether we update `pseudo_density` after the physics or not (as long as any such update is done before running the dry to wet conversion). The "saving `qv`" approach would actually become non-conservative (and unambiguously wrong) if we did start updating `pseudo_density` in a future version.

Even in the current code, I said that these two fixes are equivalent, but that's not exactly true. What I should have said is that **if both `pseudo_density` and `pseudo_density_dry` are not updated**, then conservation requires us to use **the same factor** to go from dry to wet after P3 as was used to convert from wet to dry before P3. One reasonable choice of factor would be the `pseudo_density` one, and another would use the initial value of `qv` (which therefore would have to be saved). However, since P3 does not run immediately after the dynamics, the `pseudo_density` and `qv` values are already "inconsistent" with each other by the time P3 runs (due to `qv` updates in SHOC or previous substeps). So these two fixes are not strictly equivalent (though I couldn't tell you *a priori* whether there's a clear systematic difference, and any difference is likely quite small).

I would also say that, assuming that fixing this does solve the conservation issue, either approach would probably be better than passing wet mixing ratios to P3, since as you say we know that the wet mixing ratios will be systematically "biased" low relative to dry mixing ratios.

**Comment by PeterCaldwell** [comment]
So I think we're in agreement that the fix is for `calculate_wetmmr_from_drymmr` to compute `qwet=qdry*(dpdry/dpwet)` instead of `qwet=drymmr/(1+qv_dry)` (and similar for `calculate_drymmr_from_wetmmr`). Does anyone disagree? Does anyone want to actually implement this easy fix ;-)?

**Comment by oksanaguba** [comment]
i would volunteer (just left a comment in another issue).
