### ISSUE TITLE
Need to fix parameter list read in rrtmgp interface - EKAT YAML parser unable to handle single precision inputs

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2234]
Found during a single-precision build of the standalone tests, the following code snippet 
```
  m_icecloud_threshold = m_params.get<Real>("ice_cloud_threshold",1e-12);  // Default = 1e-12
```
produced a runtime error:
```
due to unexpected exception with message:
  /home/asdonah/sandbox_1/scream/externals/ekat/src/ekat/std_meta/ekat_std_any.
  hpp:144: FAIL:
  src.isType<ConcreteType>()
  Error! Invalid cast requested.
     - actual type:    d
     - requested type: f'.
```

Changing `Real` to `double` in the code snippet fixed the issue.  Note, `rrtmgp` also has `Real` parameters read from the input YAML but we haven't seen the issue because rrtmgp standalone doesn't build in `sp`.  If we ever go to support `sp` for homme and rrtmgp we will encounter this error.

Proposed Solution (open for discussion)
1. Change all instances of `.get<Real>(...)` to `.get<double>(...)`
2. Change the `ekat_std_any` to support single precision parsing.

**Comment by bartgol** [comment]
The yaml parser must decide what format to use for all decimal numbers it reads. I chose double so that we could store more precision, but that's irrelevant: whatever we pick for the yaml file parser (float or double), the build that uses Real=the-other-one will not have the same fp type.

Whenever reading/setting floating point numbers from a parameter list, I recommend using double as type.

Your solution 2 is technically "ok", but I don't like if ekat goes "well, you asked for double, but that's a float, so I'm gonna go ahead and return it to you anyways, cause I think that's fine". I don't like to _assume_ on behalf of the user (cause when you assume you know what you make, right?).

**Comment by AaronDonahue** [comment]
That's a fair point.  Then this issue should switch to just, we need to change any yaml parameter get that apply "Real" to use "double" instead.

**Comment by AaronDonahue** [comment]
right 👍
