### ISSUE TITLE
Add derived output variable for geopotential height

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/scream#2285]
I was trying to plot geopotential height in E3SM Diags. The closest equivalent variable I could find was `VerticalLayer` variable. But it is defined relative to above ground whereas geopotential height should be defined relative to sea level. See plot below.

It would be great to add another derived variable that would provide height relative to sea level. I think we only need it for mid-points.

![image](https://user-images.githubusercontent.com/15743046/231614233-1dbd553d-5ad7-4b9a-9a24-7df93f0c08a5.png)

**Comment by bartgol** [comment]
Assigning to Aaron, since he wrote most of our diagnostics and might know better where/how to fix/add this.

**Comment by tcclevenger** [comment]
Is this not what `VerticalLayerMidpointDiagnostic` does? When it computes it `z_int`, it does so with boundary condition 0. Implementation outline
```
calculate_dz(pseudo_density, p_mid, T_mid, qv_mid);

const Real surf_geopotential = 0.0;
calculate_z_int(dz, surf_geopotential=0);
calculate_z_mid(z_int);

```
Shouldn't this compute the vertical layer height from 0? Elsewhere, `phis` (topography field) is used as the boundary condition.

**Comment by PeterCaldwell** [comment]
I think Chris wants `geopotential_height = calculate_z_int(dz,surf_geopotential=phis)`. In other words, he wants the height at 500 mb relative to sea level even if we're looking at the grid cell over Mt Everest.

**Comment by golaz** [comment]
@PeterCaldwell , @tcclevenger : indeed, you can see from the middle panel above that there is no signature of the terrain for the gropotential height at 500 hPa in ERA5 because it is defined relative to sea level height. Using `geopotential_height = calculate_z_int(dz,surf_geopotential=phis)` should accomplish what we want.

**Comment by AaronDonahue** [comment]
@tcclevenger , I think the `calculate_z_int` assumes a constant argument for surf_geopotential.  I see two strategies we can use, one would be to overload `calculate_z_int` to also accept a view for `surf_geopotential` or within the diagnostic do a parallel_for loop which calls the existing `calculate_z_int` and pass `dz(i,k)` rather than `dz` with the appropriate `phis(i)`.  Here i,k are column/pack respectively.

**Comment by PeterCaldwell** [comment]
Couldn't we also do 
```
height_above_ground = calculate_z_int(dz, surf_geopotential=0);
geopotential_height = height_above_ground + phis;
```

It is a bit weird that calculate_z_int requires a starting value and operates on arrays of columns(?) at once, but doesn't allow you to vary that starting value across columns. Perhaps I don't understand how it works, but if I'm right, it seems like we should either always assume the starting level is zero or allow it to read in arrays for surf_geopotential?

**Comment by bartgol** [comment]
> It is a bit weird that calculate_z_int requires a starting value and operates on arrays of columns(?) at once, but doesn't allow you to vary that starting value across columns.

`calculate_z_int` works on a single column worth of data. In fact, it's supposed to be used inside a parallel region.

I think the only change to do is in the `VerticalLayerInterface` diagnostic. Right now we do

```
  // Set surface geopotential for this diagnostic
  const Real surf_geopotential = 0.0;
 ..
 Kokkos::parallel_for (...
    PF::calculate_z_int(team,num_levs,dz_s,surf_geopotential,z_int_s);
 );
```
while instead we should expose `phis` as another required field, and use that when computing z_int. We don't need to duplicate this into another class, we can just do different things depending on input params. Personally, I would
- Create two diags names: "z_int" and "geopotential_int". Both of these keywords will create an instance of VerticalLayerInterface diagnostic.
- When creating the diag, set in the param list a bool param, like "From sea level". If true, we set phis=0 in the impl, otherwise we expose phis as required field.
