### ISSUE TITLE
Model init issue with screami_ne30np4l128_ifs-20160801_20220909.nc

### ISSUE THREAD

**Issue by gsever** [E3SM-Project/scream#2389]
Hello E3SM team,

Re-posting from https://github.com/E3SM-Project/scream/issues/2381#issuecomment-1593159091 per @ndkeen's suggestion.

I am running the SCREAM model on ALCF’s ThetaGPU. Recently, I have encountered an error using the ne30pg2 configuration with screami_ne30np4l128_ifs-20160801_20220909.nc file as initial conditions. The error (during model initialization stage) reads as `Bad dphi, dp3d, or vtheta_dp; label: 'DIRK Newton loop np1 see hommexx.errlog.8.1` Has anyone encountered a similar error recently?

Issue https://github.com/E3SM-Project/scream/issues/2084 mentions a similar problem (for ne120) and commented that the 128 vertical levels case is not suitable for low-resolution setups. (Despite successful attempts reported #2381). Could anyone confirm that those successful runs are using screami_ne30np4L128_20221004.nc input file? If so, what is the actual initialization datetime of that file and which dataset it originates from? 

I can run the model fine (well ~ 7 months to be more accurate without wind related CFL error) with default L72 init file: screami_ne30np4L72_20220823.nc. I also confirm that the model can integrate successfully for 1-year using the default 128 levels file  screami_ne30np4L128_20221004.nc (finished a test run yesterday).

For testing (of DYAMOND1 setup), it would be great to make the model run with IFS init file, screami_ne30np4l128_ifs-20160801_20220909.nc

My version of SCREAM is from 20221219 (sorry no git log/hash). I use the attached Python script to build a case, then run e3sm.exe on multiple GPUs (8 for most ne30 runs). 

[gs_run_scream_txt.txt](https://github.com/E3SM-Project/scream/files/11772729/gs_run_scream_txt.txt)

Thanks,

**Comment by bartgol** [comment]
A bad dphi error at init time usually points to a bad IC file, meaning bad dyn state (T, qv, ps, or horiz_winds). The log file mentioned by the error should contain more info.

That said, IIRC DIRK does not run at init time, so this is not, per se, a model init error.

**Comment by PeterCaldwell** [comment]
SCREAM has not been officially released and unfortunately the SCREAM team doesn't have the funding to support outside users at this time. This is why you haven't been getting much traction on your questions. That said, the code is open source because we welcome people to run it at their own risk. We would also like to help to the extent we can afford to. 

As noted above, your error is our generic message for a bad dynamics state - this is a typical way the model fails. Are you sure this is happening in the first timestep? I'd suggest looking in *all* the log files to see how many steps you got and whether there are any other useful messages. If you wrote output, does the output look weird? https://github.com/SEATStandards/ncvis is a nice viewer for unstructured netcdf data like SCREAM. 

Note that SCREAM doesn't have a deep convection or gravity wave drag scheme, so it isn't guaranteed to be stable at ne30 (though our experience is that it is). 

I didn't realize we *had* an ne30 initial condition for DYAMOND1. @brhillman - do you expect this file to actually work?
