### ISSUE TITLE
``FieldLayout`` with new FieldTag

### ISSUE THREAD

**Issue by odiazib** [E3SM-Project/scream#2602]
In order to use the ``AtmosphereInput class`` to read a variable from a netcdf file, one needs to pass the variable’s layout, which is an instantiation of the ``FieldLayout`` class. To construct a FieldLayout instance, we need to pass a FieldTag (an enum) and an integer. 

For example, 
```
FieldLayout scalar_refindex_real_sw_layout { {SWBAND, NREFINDEX_REAL},
                                     {nswbands,
                                      refindex_real} };
```
The limitation with the FieldTag enum defined [here]( https://github.com/E3SM-Project/scream/blob/7cb3c208c7a9367b55ee656de794533ed2e9dbfe/components/eamxx/src/share/field/field_tag.hpp#L27) is that one needs to add a new enum if the name of a dimension from a variable in the netcdf file is not listed in this part of the code. 

For example, for the layout of the variable `refindex_real_sw` with the following information:
```
double refindex_real_sw(sw_band, refindex_real) ;
                refindex_real_sw:long_name = "real refractive index of aerosol - shortwave" ;
```
One needs to add two new enums to the list of FieldTag. Note that in FiledTag ,there is also an enum with name of [ShortWaveBand](https://github.com/E3SM-Project/scream/blob/7cb3c208c7a9367b55ee656de794533ed2e9dbfe/components/eamxx/src/share/field/field_tag.hpp#L101) with name ``swband``, which is equivalent to the first dimension of `refindex_real_sw`, ``sw_band``, but one cannot use this tag because of the underscore symbol “_”.  

As the comment [here]( https://github.com/E3SM-Project/scream/blob/7cb3c208c7a9367b55ee656de794533ed2e9dbfe/components/eamxx/src/share/field/field_tag.hpp#L36), is there a better way or more flexible way of adding new field tags? Or can one have the option of using a std:string instead of FliedTag to set a new layout?
```
For example, 
FieldLayout scalar_refindex_real_lw_layout { {“sw_band”, “refindex_real”},
                                     {nlwbands,
                                      refindex_real} };  
```

**Comment by bartgol** [comment]
I'm going to start working on this next.

**Comment by bartgol** [comment]
I think it's about functionality. Currently, our list of tags is limited. When we do I/O, we must deal with field layouts and tags, and the name of the dimensions in the nc file is determined by our existing tags names. However, that is a limiting factor when dealing with pre-existing nc files where the dimensions have a different name. Sure, one can pre-process the files to change something like "swbnd" to the EAMxx version "swband", but that adds unnecessary work and data duplication. And adding a new FieldTag just for the sake of having it linked to the correct nc dim name is nonsense.

There are two direction I was exploring.
- Turn FieldTag into a small struct, storing an enum as well as a string: this allows to have different versions of the same FieldTag, which simply use different string labels for it. This is imho the cleanest way, but it requires some change through most of the code that uses layouts.
- Get rid of all the "special" field tags (such as `SWBAND`, `LWBAND`, ...), and replace them with `CMP`. This is easier to impl when it comes to writing output, but it requires some more info from input file when it comes to reading input (e.g., what label to associate to CMP in the layout `<COL,CMP,LEV>` when reading it from nc file, since the "CMP" dimension may correspond to "swbnd" in the nc file).

**Comment by rljacob** [comment]
mentioning @jayeshkrishna

**Comment by bartgol** [comment]
Rob, I think this is entierely an EAMxx issue. No need to waste time for the scorpio folks.

**Comment by bartgol** [comment]
This is no longer an issue since #2776 was merged.
