### ISSUE TITLE
IO doesn't O if freq < timestep

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/scream#2891]
To repro, take ne4pg2_ne4pg2 res whose timestep is 1 hour, set an instant output stream with frequency of 30 mins. 

The result: the very first step is written, but nothing afterwards. 

This seems kind of weird because obviously every step should in theory be an output step. In the code, I thought the output manager checks if the step is an output step by doing that logic, irrespective of freq < timestep or freq > timestep (but I could have misunderstood).

If the code is indeed working like intended, then we can document the behavior and close this issue. 

See internal outputs https://acme-climate.atlassian.net/wiki/spaces/EAMXX/pages/4334223933/EAMxx+ERFaer+production from a recent run using commit https://github.com/E3SM-Project/scream/commit/29bdb81 on branch https://github.com/E3SM-Project/scream/tree/mahf708-ff-a73d48a

**Comment by whannah1** [comment]
While this does seem like a "bug", it also seems like it should be considered "user error" that would really only be encountered by accident. I'm all for adding a check to make sure the output period is equal or longer than than the time step, but we shouldn't necessarily try to protect against all types of user errors like this, simply because there's too many possibilities to consider and we don't want to add constraints that inadvertently make future experimentation difficult.

**Comment by AaronDonahue** [comment]
I agree with Walter for this case.  We also don't want the user to request 30 min timestep and then we provide 1 hourly because thats the default timestep, and have them get quite confused by the output.  Assuming they don't look at the `time` variable.

That being said, Having checks with warnings are never bad, so I would be inclined to add a check that the frequency is less than the timestep.

**Comment by AaronDonahue** [comment]
agreed on not writing the first step if no output should be written at all.  But are you saying that if someone requests output at a frequency of say 10seconds in an ne30 run which is taking a timestep every 30minutes we should default to giving them output at a frequency of 30minutes?

**Comment by bartgol** [comment]
I agree with @whannah1 here. I don't think we should allow this use, cause it's misleading at best. I find it confusing to request output every 30min and getting an output file with output every 1h. And confusion is the cause of a lot of bugs/mistakes: anyone seeing a filen with `_nhours_x1` in the name but only 2h output inside would have a hard time figuring out whether that's fine or if the file is corrupted/wrong.

If we want to avoid empty files (I can see why that's annoying :) ) we can check compatibility of freq and dt at buildnml time (I think we have all we need by then).

As for why this happens, the reason is that IO computes the timestamp of the next write, and then simply waits to write until t==next_write_ts. The assumption that dt<=output_dt is crucial here, but from the design point of view it seemed obvious. Finally, you do get t=0 output (for INSTANT output) since that's always saved, regardless of dt and output_dt (unless you explicitly disable it).

**Comment by bartgol** [comment]
I agree that the result you are seeing is confusing, so I'm reopening. However, I think the solution is to notify the user during buildnml. At least for CIME cases, this should help avoiding confusing results.

We can also add an online check (for standalone eamxx sake), where we verify at run time that `dt<=(next_write_ts - last_write_ts)`.
