### ISSUE TITLE
Bug in `AtmosphereDriver::set_initial_conditions()` for Physics PG2 Grid

### ISSUE THREAD

**Issue by mjs271** [E3SM-Project/scream#3018]
In working on the DAG constructor, and running the `homme_shoc_cld_spa_p3_rrtmgp_pg2_dp` case, I discovered, with the help of @bartgol, that, for the PG2 grid, the `tracers` group and the `nc_nuceat_tend` and `ni_activated` fields do not appear to be initialized.

I believe this is due to the logic control used within the `process_ic_field()` lambda
```c++
if (ic_pl.isParameter(fname)) {...}
else if (fname == "phis" or fname == "sgh30") {...}
else if (not (fvphyshack and grid_name == "Physics PG2")) {...}
else if (fvphyshack and grid_name == "Physics GLL") {...}
```
Specifically, the final 2 evaluate to the same truth condition when `fvphyshack == true`, and this results in the `tracers` group being processed twice for the Physics GLL grid and never for the PG2 case, while the fields `nc_nuceat_tend` and `ni_activated` never get processed.

**Comment by bartgol** [comment]
The ni_activated and nc_nuceat_tend fields are set to 0 in CIME runs, but are not set to 0 in standalone runs. Nevertheless, the code never complains. This seems odd, and it hints at some checks in the AD (or maybe in the AtmProc base class, for P3) that don't happen correctly. In theory, if a field that is an atm input is uninitialized (detected by its time stamp still being invalid), the AD should error out at the end of the init sequence. On top of that, I _think_ we have checks in the AtmProc base class that ensure all inputs have a valid time stamp (i.e., they were loaded/computed before) at the beginning of the run method.

As for tracers, the issue is that the PG2 field is appearing as initialized, while the GLL field is appearing as not initialized. The latter should only be a temporary stepping stone in the init sequence, so one of the following should happen:
- find out why the GLL field timestamp is not set, and fix it
- be more quick at deleting these "stepping stone" fields from the FM.

I have to look at Mike's code to see exaclty where the DAG is checked. The fact that we see PG2 "valid" makes me think he does the check _after_ the call to `initialize` for the atm proc, at which point Homme should have already deleted the field. However, I think Homme only removes the field from the atm proc. @ambrad I think you had a comment in the code somewhere regarding this feature (I can't find it, maybe it got deleted), that perhaps calling `remove_field` in HommeDynamics wasn't enough, and the AD needs to do something.

I think we should add a new "reserved" group name, for fields that are only needed to read ICs, something like "IC_READ_TEMPORARY". The AD can then programmatically delete these fields from the FieldManager as well, once the IC read sequence is completed.

@mjs271 as a temporary hack to check if the issue is indeed that the GLL fields in the FieldManager are still there, you could try to manually "empty" the GLL FM after IC are read. You could actually just plain remove that FM:
```c++
  m_field_mgrs.erase("Physics GLL");
```
and see if you still have the missing tracers field in the DAG.

**Comment by ambrad** [comment]
@bartgol I think the comment you mean is this: https://github.com/E3SM-Project/scream/blob/a269ef91a3da65ee4e23f4e33736684366046b4d/components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.cpp#L185 For more info, search the code for "[CGLL ICs in pg2]". In particular, `AtmosphereDriver::initialize_atm_procs` has the code to remove the "Physics GLL" field manager.

**Comment by bartgol** [comment]
> @bartgol I think the comment you mean is this:
> 
> https://github.com/E3SM-Project/scream/blob/a269ef91a3da65ee4e23f4e33736684366046b4d/components/eamxx/src/dynamics/homme/eamxx_homme_process_interface.cpp#L185
> 
> For more info, search the code for "[CGLL ICs in pg2]". In particular, `AtmosphereDriver::initialize_atm_procs` has the code to remove the "Physics GLL" field manager.

Ah, yes, we ARE removeing the CGLL field mgr. Since @mjs271  is still seeing the CGLL field in the DAG, we either a) are not removing it correctly from the atm proc internals, or b) we are building the DAG before it gets removed. My guess is b (that's definitely what is happening in master: we don't include IC info in the DAG, that's what Mike is adding in his soon-to-come PR).

**Comment by mjs271** [comment]
So I just checked back in on this and figured out a couple of things:
1. This test is run by its own `.cpp` file and doesn't actually call AtmosphereDriver.initialize() but rather:
```
ad.initialize_fields ();
ad.initialize_output_managers ();
ad.initialize_atm_procs ();
```
2. The issue I describe still remains, though it could just be a consequence of the non-standard procedure.

Here's the DAG I create after the above initialization calls, that is called from `homme_shoc_cld_spa_p3_rrtmgp_pg2_dp.cpp`, indicating that `nc_nuceat_tend` and `ni_activated`, which are required by P3, appear to be missing.

![final_dag](https://github.com/user-attachments/assets/d7591001-23f5-4432-9454-deca4bc8db9a)

@bartgol @tcclevenger

**Comment by bartgol** [comment]
@mjs271 a few comments:

- It's ok to call the individual `initialize_XYZ` functions. That's what happens in CIME runs too. The monolithic `initialize(..)` fcn is only used by standalone eamxx
- CIME cases do set `nc_nuceat_tend` to 0 during init, so they are ok. We should prob to the same in our standalone test
- I think we should throw an error if, after IC's, we still have MISSING fields.

**Comment by mjs271** [comment]
Cool--thank you for the info, @bartgol!

Shall I close this then? Any interest in tracking points 2 and 3 from your preceding comment?

**Comment by bartgol** [comment]
I think we could address it in your DAG pr, if you think it's appropriate.
