### ISSUE TITLE
Empty (zero-sized) monthly outputs

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/scream#3026]
In the decadal AMIP run, we have run into a handful of times in which the monthly average output stream files will have zero-sized time dimension, and consequently no data. So far, this has been seen in the following output files in that run:
```
output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1995-08-01-00000.nc
output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-09-01-00000.nc
output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-12-01-00000.nc
output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1997-11-01-00000.nc
output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1998-02-01-00000.nc
```

**Comment by crterai** [comment]
It looks like they're all written during a job that either failed or was cancelled. I zgrep'ed the files in the `atm.log` files and they all don't end with `.gz` which makes me think that they either failed or were canceled. And it's not like these all failed right after the end of the month. 
```
[terai@login07.frontier run]$ zgrep "output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1995-08-01-00000.nc" atm.log*
atm.log.2214821.240813-182511:[EAMxx::output_manager]      FILE: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1995-08-01-00000.nc
atm.log.2214821.240813-182511:  file name: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1995-08-01-00000.nc
[terai@login07.frontier run]$ zgrep "output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-09-01-00000.nc" atm.log*
atm.log.2320113.240830-045214:[EAMxx::output_manager]      FILE: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-09-01-00000.nc
atm.log.2320113.240830-045214:  file name: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-09-01-00000.nc
[terai@login07.frontier run]$ zgrep "output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-09-12-00000.nc" atm.log*
[terai@login07.frontier run]$ zgrep "output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-12-01-00000.nc" atm.log*
atm.log.2329614.240904-021205:[EAMxx::output_manager]      FILE: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-12-01-00000.nc
atm.log.2329614.240904-021205:  file name: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1996-12-01-00000.nc
[terai@login07.frontier run]$ zgrep "output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1997-11-01-00000.nc" atm.log*
atm.log.2398335.240912-174454:[EAMxx::output_manager]      FILE: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1997-11-01-00000.nc
atm.log.2398335.240912-174454:  file name: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1997-11-01-00000.nc
[terai@login07.frontier run]$ zgrep "output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1998-02-01-00000.nc" atm.log*
atm.log.2440253.240915-011135:[EAMxx::output_manager]      FILE: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1998-02-01-00000.nc
atm.log.2440253.240915-011135:  file name: output.scream.decadal.monthlyAVG_ne30pg2.AVERAGE.nmonths_x1.1998-02-01-00000.nc
```

**Comment by bartgol** [comment]
@PeterCaldwell @brhillman @crterai @rljacob @AaronDonahue , and others who are interested in the topic.

@mahf708 and I had quite a long thread on slack related to this, talking about what's expected of EAMxx in terms of output integrity, and how to compromise safety and potential code/perf impacts.

As you know (if you are reading this issue), currently EAMxx has the zero-sized file problem. The reason is that we don't explicitly flush files until they are closed, and they are not closed until either a) the run completes and the system is shut down (this also happens (or should happen) if an exception is thrown **from inside EAMxx**), or b) we need to write another step and find out it doesn't fit in the previous file.

To avoid this issue, I proposed on slack to add an explicit file flush every time we write a restart. Note, not just "flush the restart file", but also "flush the corresponding output file". Naser is pointing out that this does not cover all use cases, since he foresee something like this:
- start run with monthly avg output, restart every 20 days
- run reaches restart at 20days. Output file is still empty, so no flush for it
- 10 more days, and the monthly avg is done, but we don't flush the file (we only flush at restarts, remember?)
- run crashes before next restart.

In this case, you _can_ restart from day 20, without losing anything from before the restart. However, you _could_ have flushed the output and have the monthly avg file, since the crash was after the avg was done.

So the question is: what do model users expect in terms of "integrity" of their output files? I see two (well, three, but the third has prob very few disciples) school of thought:
- flush only at restarts: if something happens after restart, you will likely have to restart from there anyways, so why spending effort ensuring stuff computed after last restart was flushed?
- flush whenever a file is full: even if not a restart time, if a file is full, why not writing it out immediately, in case you want to look at it?
- flush every time you write a snapshot: can't be left with missing output if you _always_ flush, amiright?

Note: this question regards _default_ behavior. We _already_ allow the user to set a flush frequency via yaml file (I don't know if someone is using it, and I don't know if it's tested, so YMMV), so it _is_  possible to request higher frequency file sync. It's just not the default behavior.

Some facts to consider:
- @jayeshkrishna is advising to be cautious with file flushing, since it may negatively affect performance.
- @mahf708 has done some tests, and says perf impact of intensive file flushing is well below 5% (he may be able to share more precise numbers)
- the falcons are 3-2 and I'm starting to think we _may_ make the postseason for once...

**Comment by crterai** [comment]
I think 'flush only at restarts' is enough to ensure integrity of our output (at least in the decadal and Cess instances) when we're running production simulations. It would be nice to have 'flush at restarts AND whenever a file is full' but I'm fine with making that something you turn on on your own in yaml files.
