### ISSUE TITLE
P3 to treat temperature and tracers similarly when it comes to tendencies

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#365]
Right now, as it is implemented, P3 backs out a tendency for tracers (as `FQ += (qnew-qold)/dt`), but the same is not done for the temperature. This is confusing. It is probably best to use the same approach for both (and, probably, for all parametrizations).

**Comment by PeterCaldwell** [comment]
I totally agree. This has driven me batty for years.

**Comment by bartgol** [comment]
Note: this is orthogonal to whether a parametrization should compute the tendency or the updated state (and let the tendency be backed out later from outside). We can discuss about that separately. Here, we just want a uniform approach within the P3Microphysics atm process.

**Comment by AaronDonahue** [comment]
But it does expose a greater issue about whether or not physics sends tendencies or states to the dynamics to deal with.  The current CAM-ithic approach splits them up and this can be confusing.

**Comment by bartgol** [comment]
Physics doesn't talk to dynamics directly. It talks to the AD infrastructure. The infrastructure should deal with what we do for coupling.

We could even write a "TendencyBacker" atm process, that wraps another atm process, and backs out a tendency for one (or more) of its computed fields. This would allow the maintainers of the wrapped atm process to not worry about coupling, and tendency-vs-state. Separate concerns.

**Comment by PeterCaldwell** [comment]
@bartgol - I must admit I'm totally confused what you're talking about. When I expressed enthusiasm, I hadn't noticed you were talking about P3. I (and I think Aaron) are traumatized by how dp coupling treats T and q differently. I don't understand what you mean about P3 doing this. Could you provide a git permalink to the location in the code that you don't like?

**Comment by AaronDonahue** [comment]
Luca and I had already discussed this a little bit via Slack when talking about his DAG PR.  I think the main point of this issue is that the current definition of the P3 interface with the AD is inconsistent between how Q tendencies and the T tendency are handled.  When I set them up I followed the CAM-ithic convention.  But moving forward we should remedy this.  It also brings up the more important point that any of the new processes ported may try to follow the old paradigm.

Luckily, the way we are setting up the AD means that we will be in control of the layer between physics and dynamics.  So we should be able to finally right this wrong once and for all.  So main issue, fix P3 now, bigger issue, make sure other processes are also correct in the implementation.  

At least I think that's what the issue is getting at.  @bartgol ?

**Comment by bartgol** [comment]
I haven't looked to what micro_p3.F90 does in cam. I only looked at scream_p3_interface.F90, and saw [this](https://github.com/E3SM-Project/scream/blob/f7625ff83e3664016587607c97e196d80397aa83/components/scream/src/physics/p3/scream_p3_interface.F90#L318). I think that p3_main_f90 was just an initial tentative by Aaron of hooking up the f90 version of p3 to the AD, to be able to have more realistic checks for the driver, so it may not be what we will do in the end. However, I felt like opening an issue, so we make sure this is discussed before the final C++ interface of P3 is finalized.

**Comment by PeterCaldwell** [comment]
Ok, sounds good. Maybe a question for the AD telecon tomorrow.

**Comment by PeterCaldwell** [comment]
@AaronDonahue - does PR #804 address this problem?

**Comment by bartgol** [comment]
I'm pretty sure this is no longer an issue. The P3 atm proc has a qv_prev and T_prev, so I'm _assuming_ it backs out tendencies for qv in the same way as it is done for T. @AaronDonahue , if I'm wrong, please, reopen.

**Comment by AaronDonahue** [comment]
No, this has been handled.  Thanks for closing @bartgol
