### ISSUE TITLE
Most BFB tests aren't actually being checked on GPUs?

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#381]
I think I've discovered a flaw in our BFB unit testing on GPUs. A lot of our tests follow a paradigm where you come up with 16 different sets of input you want to test, then try to stuff all 16 of those cases into a single set of input Spacks so we can get their solutions by a single call to the C++ version of our function of interest. To do this, data is stuffed into these input Spacks via `for (Int s = 0; s < Spack::n; ++s)`  statements... but Spack::n ==1 on GPUs. Thus this loopy assignment doesn't fail, but it only checks the first case we wanted to test!

[p3_autoconversion_unit_tests.cpp ](https://github.com/E3SM-Project/scream/blob/master/components/scream/src/physics/p3/tests/p3_autoconversion_unit_tests.cpp) is a canonical example. Look in particular around line 76.

I've confirmed empirically that this is the case by putting print statements in the code on device for Spack::n and also just printing out the output from the autoconversion bfb test... and there's only 1 output value.

I'm not sure what a better testing paradigm would be... making each Spack just repeat a single value and looping over each case we test on CPUs is wasteful but trying to stuff lots of data into a single function call on GPUs doesn't work. Ideas? @jgfouca , @pbtoast , @ambrad , @bartgol ? Also of interest to @pressel , @xyuan , @singhbalwinder .

**Comment by ambrad** [comment]
I agree with Peter: rewrite the unit tests to have 16 (or whatever) entries in a view, and duplicate values within a pack. It's a negligible cost on CPU.

**Comment by ambrad** [comment]
I'm looking at [the code starting here](https://github.com/E3SM-Project/scream/blob/71e66df00e4a2022f39e1ea38f9c3086a2428d56/components/scream/src/physics/p3/tests/p3_autoconversion_unit_tests.cpp#L60) and going to [here](https://github.com/E3SM-Project/scream/blob/71e66df00e4a2022f39e1ea38f9c3086a2428d56/components/scream/src/physics/p3/tests/p3_autoconversion_unit_tests.cpp#L106).

You could put a loop over all of that, with (max_pack_size + Spack::n - 1)/Spack::n iterations. (For simplicity, you could assume Spack::n % max_pack_size == 0, which is a safe assumption. Then there are max_pack_size/Spack::n iterations with no remainder in the last iteration.)

Then in each iteration with iterate `it`, instead of starting with `cwadc[0]`, start with `cwadc[Spack::n*it]`. But everything else is the same.

This is a unit test, so no need to care about dispatching multiple times. As it is, the BFB math calls dispatch at each call.

This would add ~5 lines to each of these BFB unit tests.
