### ISSUE TITLE
[AD] Unit tests for field and field repository

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#561]

**Comment by AaronDonahue** [comment]
@bartgol , when you have a chance could you list some ideas of unit tests you are thinking of?

**Comment by jeff-cohere** [comment]
Hey @bartgol and @AaronDonahue , I see some unit tests for fields and field repos in `src/share/tests/field_tests.cpp`. Are there additional tests that you had in mind here?

**Comment by bartgol** [comment]
One thing that might be better checked is whether using a field with two different scalar types works as expected. Maybe, in the process, we might realize we need to expose some utilities for reshaped views, I don't know.

For instance, let's say we have a field with _physical_ layout (3,9). It'd be nice to do this:
1. Request allocation for `Pack<Real,N>`, with whatever N (power of 2, obviously).
2. Get reshaped view as `Real**`, and fill it (say, all ones).
3. Get reshaped view as `Pack<Real,N>**` and do a column reduction (using ekat's util)
4. Check the reduction is the expected one.

Notice that in 2 and 3 you need to use bounds coming from FieldLayout, *not* view's extents (due to padding) when doing loops. This is where I wonder if we should/could offer some helpers for users, to prevent them looping on the wrong bounds.

**Comment by jeff-cohere** [comment]
Have we documented layouts anywhere? We've got a lot of concepts on top of Kokkos (which already isn't super-well documented), and I worry about the various ways in which people can put things together improperly, with unpredictable results.

**Comment by bartgol** [comment]
I don't think so. We need to take some time off to write down all the documentation we need.

**Comment by jeff-cohere** [comment]
If you can point me at examples of how they're used and source for how they're implemented, I can write something up. Those things would help me write these tests, too.

**Comment by PeterCaldwell** [comment]
I think #650 closes this issue. @jeff-cohere or @bartgol , would you mind checking/closing?
