### ISSUE TITLE
A simple getter interface in field repo to grab pointer to a field

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#639]
The field repository is currently a map of a field name to a separate map.  That map is from field identifier to the field itself.  This was done because field identifiers are unique but one field name can point to multiple field identifiers.  Sometimes we need a way to quickly get a field given it's name and the grid it is defined on.  This can be done by looping through the map of field identifiers to fields, but a simple getter function in the field repo could simplify this process.

**Comment by AaronDonahue** [comment]
@brhillman , I've made an issue for the feature we discussed on the scream slack channel.

**Comment by bartgol** [comment]
This is assuming that for each grid, there will only be *one* version of each field. This is probably true, but might be limiting in the future.

One scenario where I think there might be different copies is if some field should be used with different layout in different parts of the atm code. Say a field that has layout (ncols,ntracers,nlevs), which in some other parts of the code might be more efficiently used if stored as (ncols,nlevs,ntracers).

A few questions:
1. do we want to support such a case? Meaning, do we allow a field to be stored in two different ways? Or can we error out (due to unmet dependencies) and force one of the two to adapt to the other?
2. If we decide to support this scenario, how do we do it?

Answering NO to 1 would likely allow a way to do `field_repo.get_field(name,grid_name)`, with increased simplicity. However, what if we have a field defined at level midpoints as well as level interfaces. Right now, one can give the same name, and the FM would treat them as different fields. E.g, pressure (ncols,nlev) and (ncols,nlev+1) are different, despite being on the same grid and having the same name. This sparks more decisions to make:

- should we allow two fields with the same name to have different dimensions? The classic examples is field at midlevel or interfaces.
- If the answer is no, we are forcing people to use different names for midpoints and interface quantities. Are we ok with that? If so, then we should have pre-defined suffixes for this distinction. And no suffix should imply a pre-defined position (mid or int), but which one?
- if the answer is yes, then the map `field_repo.get_field(name,grid_name)` cannot be implemented.

Another solution to the mid-vs-int dilemma: should midpoints and interfaces be considered "different grids"? I was thinking not, but maybe that would solve the problem of same name, since pmid and pint would live on "different" grids...

**Comment by AaronDonahue** [comment]
@bartgol , these are good points.  I'm leaning towards not allowing the same variable name on the same grid but with slightly different dimensions, like your mid-level vs. interface example.  If nothing more than the fact that it could be a persistent and difficult bug to find if a developer thinks they are somehow grabbing mid-level but are really grabbing interface (or vice versa).  I would suspect the difference between an interface an mid-level is small enough that the code would remain stable if not incorrect.

That being said I see two options.  
-Your aforementioned explicit name convention, something like "X_mid" vs. "X_int" to specify that X is defined at mid-level or on the interfaces.  
-Another option would be to all field_identifiers to themselves be a map to "interface" or "mid-level" versions.  So you can query FID by name and grid and then use X.at("midlevel") and X.at("interface").  Returning an error if one of these options hasn't been defined.

per the first option, I think if we just go with different variable names then a default would be midlevel and interface would perhaps be the specialized name.  At least for most variables.  It may make sense to have something like `pmid` and `pint` because of how often these are used.  But `q` and `T` for example are most generally used at midlevel.  So making every variable have to be `q_mid` or `T_mid`, etc. would be a bit tedious and would probably lead to a lot of `_mid` being written.

Per the second option, we would need to adjust the field_identifier class to detect when using NLEV for the level TAG vs (NLEV+1) for the level TAG in the layout declaration.  Not sure how easy that would be.

thoughts?

**Comment by bartgol** [comment]
I don't like your option 2, so I would vote against that. Option one is passable, but not really satisfactory (in my mind). Mid vs int is just a "grid" detail. If we have different names for different grids, then why not having `p_phys_mid` and `p_dyn_mid` (or something like that)?

I said passable, cause I think it's the easiest solution, and would indeed "solve" the problem. But ideally, I'd like to have the possibility of having more than 1 version of the same field (meaning same name), but with different layouts, just like with different grids. That's the whole point of incorporating the layout in the field identifier. If we don't want two "press" fields with different layout, then the layout should be pulled off of the identifier (perhaps put it in the header).

**Comment by AaronDonahue** [comment]
yeah, I'm totally comfortable with having grid subsets that represent the interface or the mid level.  We could also adopt a remapper then that interpolates between the two, if needed.

Will this impact how we designate the grid each process is on?  Or will we have the distinction of physics and dynamics and then phy_mid and phys_int as physics grid subsets?

**Comment by bartgol** [comment]
I propose an intermediate solution: we expose a method `get_field(field_name, grid_name)`, but we error out if there is more than one field with such name on that grid. So this method is "use at your own risk", in case someone, somewhere else, decides to use an unorthodox layout for that field.

**Comment by AaronDonahue** [comment]
Sounds good.  Do you want me to put the PR in?

**Comment by bartgol** [comment]
If you have time and/or need it, go ahead!
