### ISSUE TITLE
Management of components in Q

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#658]
Among the fields in the field manager, the variable Q is unique, in that it represents the entire set of components that will be advected in the dycore.  For reference, the dimensions of Q are (column,level,component).

Aside from hard-coding that the first component of Q is the water vapor mass mixing ratio, Q can have any number of other components including cloud water (liq, ice, rime, snow), cloud number (liq, ice, rime, snow) and aerosol species.

Currently the components are essentially hard-coded with the various atm. processes taking for granted that the component indexes represent specific species.  This paradigm breaks down if we, for example, switch the microphysics scheme.

The EAM approach is the `add_const` routine which adds a constituent to the index of Q.  It effectively assigns the next empty component index in Q to that constituent.  Afterwhich, a process can query the constituent index in Q with another lookup routine.  This allows for a fluid definition of the components of Q.

If we follow the EAM example we will need to create a setter function to allow Q components to be defined and catalogued.

**Comment by AaronDonahue** [comment]
I can think of a couple approaches we can take:
1. Follow EAM directly and create a `set_q_component` or `add_const` routine which will add a new constituent to the catalog of Q components and assign it an index.  We would also need to establish a "getter" function to retrieve this info by name.  Does this path mean we need a special Q sub-class of the field object to facilitate these new functions.
2.  Another approach would be to remove Q entirely from the field manager and explicitly spell out each constituent as a member of the field manager.  For example, qv, qr and qc to represent vapor, rain and cloud liquid respectively.  We would then add the group "advected" to their header info.  When the dycore fires up it would gather the group of "advected" variables and populate a local equivalent of Q that could be advected.

**Comment by jeff-cohere** [comment]
If we already have the idea of a "group" in the field repo, I prefer option 2. If I understand option 1, it requires

1. a maximum number of components (a "capacity")
2. that all advected quantities are stored in the same Field/View.

What constraints would we place upon fields that belong to the "advected" group if we go with option 2? I assume they all have to have the same dimensions, aside from maybe the number of components.

**Comment by AaronDonahue** [comment]
We do already have the concept of "group" in the field manager and there is a "getter" function to grab all fields from a specific group.

To your point, yes, option 1 requires some cap in the number of components.  Currently in EAM this is a compile time variable.  In F90 this makes sense, for the dynamics the size of the array of advected species needs to be known at compile time.  It is defined as `qsize_d` if curious.  And yes, all advected quantities would have to be stored in the same field.  So if you wanted just qv you would still need to declare the need for all of q to get at it.

As Jeff points out, there would be constraints even with option 2.  If we plan to populate a single Q array on the dynamics side of things that needs to be reasonable.  So all individual constituents would have the same layout, presumably (Column,VerticalLevel).

**Comment by jeff-cohere** [comment]
@pbosler ^^^

**Comment by PeterCaldwell** [comment]
I've always hated Q. It sounds like it should be water vapor, which is often denoted by q and it is, but it is also all the aerosols, which aren't q variables at all. It is also annoying to need to retrieve the index for each Q entry whenever you need them - it's like a mini-pbuf but without using pbuf! I think it would make much more sense to just flag all the variables in the field manager that need to be advected and otherwise allow them to be normal variables like anything else. I think this is approach number 2 that Jeff likes as well...

**Comment by bartgol** [comment]
If I understand correctly, the only place where it makes sense for all tracers to be "together" (inside Q) is when they are advected in dynamics. That's the only place where they are *all* needed at the same time, and they all undergo the *same* set of routines. Everywhere else, it makes no sense to pack them together. It only makes life complicated for other customers, since extracting a slice at a particular tracer index would create a strided view.

I think option 2 proposed by Aaron is interesting. It would also allow dynamics to _not_ register Q in the FM, but simply use it as an internal variable for "packing" the tracers. Having to pack/unpack them is not a big deal, since the phys<->dyn grid remapping already forces one to copy data from one layout to another. We might as well have one of these two layouts being a set of completely different fields.

Having each tracer to be a separate field, also allow less waste of memory _if_ two physics processes use different grids. I am thinking about RAD using a shuffled phys grid, with twin columns: I am assuming RAD does not need _all_ tracers, so it makes no sense to remap all of them to the RAD grid (like we would need to, if tracers were all packed in Q). If they are all their individual field, then we remap only what is needed.

I think we may also benefit from an auxiliary Tracers or Constituents class, which the AD might keep track of. I feel like some functionalities might be easier if wrapped in a class.

**Comment by bartgol** [comment]
> As Jeff points out, there would be constraints even with option 2. If we plan to populate a single Q array on the dynamics side of things that needs to be reasonable. So all individual constituents would have the same layout, presumably (Column,VerticalLevel).

All tracers having the same layout is not a big limitation (I think). After all, all physics fields will have that layout, presumably. That said, nothing stops us from packing tracers into Q from fields with different layouts. We currently don't support this (we don't even support packing multiple fields in phys grid into a single (packed) field in dyn grid, but that can/must be added), but we could, if it comes out we need it.

**Comment by jeff-cohere** [comment]
Great! I agree that tracers having the same layout is not a big deal--our EAGLES use case certainly permits this. I also think it'll be easier to see what's going on explicitly if we allow different physics processes to register their own fields for advection--we'll probably eliminate a whole category of bugs.

**Comment by bartgol** [comment]
Let's discuss this more on Thursday's telecon.

**Comment by AaronDonahue** [comment]
Excellent discussion, I will add this topic to the Thursday telecon agenda.

**Comment by PeterCaldwell** [comment]
Isn't this issue redundant w/ #759 ? Should we just mention this issue in that one and close this one?

**Comment by AaronDonahue** [comment]
Yes, I think this issue is essentially solved by our decision to *not* have Q in the physics and contain it just to Dynamics.  If there is not objection I think we can close this.

**Comment by jeff-cohere** [comment]
Yeah, I think this was just a starting point for the tracer discussion. I don't think there's any work associated with this issue.
