### ISSUE TITLE
Strange warning when building SCREAM

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#69]
I get the following warning when building scream locally that I don't think is related to my P3 changes.  Not sure if it is important.

```
In file included from /g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/util/scream_kokkos_utils.hpp(6),
                 from /g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/tests/pack_kokkos_tests.cpp(7):
/g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/util/scream_std_meta.hpp(68): warning #488: template parameter "T" is not used in declaring the parameter types of function template "scream::util::impl::holder<HeldType>::holder<T>(std::enable_if<std::is_base_of<HeldType, T>::value, std::shared_ptr<T>>::type)"
    template<typename T>
```

**Comment by ambrad** [comment]
@bartgol This is related to `holder` and related classes, so I've moved the assignment to you.

Weak opinion: Move `holder` and `any` to `parameter_list.hpp` so this complexity is limited to the one use case demanding it (we can be confident that only the parameter list impl will every use `any`). The motivation is to isolate whatever fallout (such as this warning) comes from this complexity to just that use case.

**Comment by bartgol** [comment]
I don't think it's appropriate to move that code to `parameter_list.hpp`. Yes, it may be the only customer, but it is logically a stand-alone piece of code. 

The compiler warning is correct, and I wondered why it didn't come up before. The issue is the enable_if, which creates a dependency on itself. I will take a look and see if there is a workaround (and also check whether we ever use that constructor).

**Comment by bartgol** [comment]
I will have a PR up in a few minutes.
