### ISSUE TITLE
[AD] Add two dictionaries of CF compliant variable longnames to be used to enforce CF compliance in SCREAM

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#699]
Variable longnames as stored in the Field Manager should be CF compliant.  This will allow the field manager to ensure that no two processes register the same variable under different names.  It will also establish a naming convention for variables that can be consistent across processes.  See https://cfconventions.org/standard-names.html

A dictionary of CF compliant long names will be needed in SCREAM.  The field manager can then query this dictionary for each new variable and throw an error if a variable is not listed.

There will be variables in the field manager that are not in the CF dictionary.  A second dictionary of SCREAM-specific variable names will be needed that can be expanded to include these variables.  By enforcing compliance with a second dictionary we can hedge against developers accidentally adding an unknown variable with no way of checking that it is in fact in the CF dictionary.

This is step 1 of getting CF compliance in SCREAM.

Addresses #527  and #528

**Comment by jeff-cohere** [comment]
Hey @AaronDonahue ,

I know we discussed creating a YAML file in which to store the CF standard field names, and we have one of those now (generated by a script in the `jeff-cohere/cf-xml-to-yaml` branch `scripts/` directory). Is that the "deliverable" for this item?

The YAML file is huge, since there are a ton of possible CF field names (and aliases). I guess that doesn't matter as long as we just use it (and presumably a second one of our own) as input to generate validation code. I don't know that we want SCREAM to require these files as data.

**Comment by bartgol** [comment]
@jeff-cohere yeah, I think it's fine. We are only going to use it to validate names (i.e., reject names that are not in that list).

**Comment by PeterCaldwell** [comment]
I think this is half-done now via #719 , right? Should we narrow this issue down to just the "create a table of CF-like names for variables that aren't already in the CF table" (via modifying this PR or closing and creating a new one)?

**Comment by jeff-cohere** [comment]
Yeah, and actually the (empty) file already exists for the SCREAM CF-like names (in `data/cf-scream-name-table.yaml`, alongside `data/cf-standard-name-table.yaml`). I think we can close this issue and just add names to that table as part of our ongoing work.
