### ISSUE TITLE
P3: autoconversion produces different nc and nr!!!

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#729]
We're using the KK2000 autoconversion scheme in P3. It computes the number of cloud drops converted to rain drops as proportional to the mass of cloud water converted to rain. But it computes the number of *rain drops* formed assuming all new rain drops are 25 micron in diameter. See https://github.com/E3SM-Project/scream/blob/6c6beacf94ee67a383ce891a308a296a771f08ea/components/eam/src/physics/cam/micro_p3.F90#L2748 . My fundamental understanding of autoconversion is that it handles growth of rain drops by diffusional growth so the number of cloud drops lost to autoconversion should equal the number of rain drops gained. MG2 and the other autoconversion options in WRF P3 do this, but KK2000 doesn't... even in its original formulation: https://journals.ametsoc.org/mwr/article/128/1/229/66243/A-New-Cloud-Physics-Parameterization-in-a-Large

@JS-WRF-SBM and @hassanbeydoun - do you agree that this behavior is inappropriate?

**Comment by hassanbeydoun** [comment]
I don't think that behavior is inappropriate. Warm rain formation is not my specialty but what I recall about stochastic formation of rain drops is that the embryonic rain drop size distribution is not connected to cloud drop size distribution in a continuous fashion. In other words, the first rain drops don't form out of the tail end of the largest cloud drops continuously but do so in spurts (they show out of nowhere!). If we thus assume that a 25 um rain drop size distribution is borne out of a say 10 um cloud drop size distribution (these are mean diameters) then the number of rain drops should be scaled by the difference in diameters of the two size distributions. If you look at eqns 32 and 35 and and set the accretion to zero in the latter, the cloud and rain number tendencies are simply scaled by the mean diameters. I realize other parameterizations attempt to conserve number in the jump between the two categories but I don't see why that would be better - just different. 

On a more pragmatic note, I prefer the KK approach for mp setups where Nc is constant or prescribed.

**Comment by JS-WRF-SBM** [comment]
Hi @PeterCaldwell 

1.  The fundamental process behind auto-conversion is solely collision-coalescence
2.   The reason why `ncautr` is different from how `ncautc` is calculated related to mass conservation. 
The cloud mode is assumed to be at the size of `1um`, while the rain mode is assumed to be at `25um` -- that means that in order to project what is the mass of the embryonic rain drops, the number cannot be conserved (while the mass conserves, but for larger mean size).
That is why `ncautr` uses solely the mass of cloud droplets, and `ncautc` calculates the current number conc proportional to the mean size of cloud droplets (involving both `nc` and `qr`).

I'm more interested in how this question was raised in the first place -- just by going through the code?

**Comment by PeterCaldwell** [comment]
Ok, thanks @JS-WRF-SBM and @hassanbeydoun - I think I was suffering from excessive-meeting-induced-brain-death when I created this issue. You're right... the KK approach is totally reasonable. I'll close this issue.

In terms of why I'm thinking about this now - I'm just going through the code. More particularly, I'm finally getting around to integrating all the bugfixes you shared with me a couple weeks ago, Koby. See https://github.com/E3SM-Project/scream/pull/714 .
