### ISSUE TITLE
[AD] SCORPIO-Interface: Indepdence of restart history vs. restart - low priority

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#796]
Currently the restart history and restart file writes are synced, i.e. they have the same frequency.  This task is more of a question.  Is it worth giving the user the ability to set a different restart history frequency at runtime?  That way they could write more frequent, or less frequent restart histories.

The idea would be to default to restart and restart history files having the same frequency.  And then if the option is exercised in the YAML file it will overwrite the default.

Note: It's not clear this option would ever actually be used.  So this is low priority.

**Comment by PeterCaldwell** [comment]
I don't think this is a good idea. The only reason to do a restart history write is because you're doing a restart and don't want your output to be corrupted. So I don't think you'd ever say "hey, I want to write a restart history without the ability to actually restart!". Conversely, if you want to restart, it's hard to imagine you'd choose to corrupt your history tapes.

**Comment by AaronDonahue** [comment]
I agree, but I thought it best to put the idea out there in case someone could come up with a credible reason why they should be independent.
