### ISSUE TITLE
Confirm variables passed between AD and surface coupler are correct

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#812]
#747 implements an initial version of AD/surface coupling but Luca wasn't sure if the SCREAM variables he passed to/from the surface coupler were correct. Balwinder will check this and flag any variables he's not sure about. 

Note that this issue is somewhat connected to our desire to use CF variable names as the long-names for SCREAM variables (#700 and other issues) in the sense that CF names may help clarify what each SCREAM variable does. This task doesn't depend on CF names, however, and only really depends on knowing what each variable truly represents.

**Comment by PeterCaldwell** [comment]
Great, thanks @bartgol . I'd like to have a separate issue for making sure variable names are used consistently *between* scream processes. I'll create that.

**Comment by bartgol** [comment]
@singhbalwinder I started a [branch](https://github.com/E3SM-Project/scream/tree/bartgol/surface_coupling_2.0) for the SC further development. I put some comments in `src/mct_coupling/scream_cpl_indices.F90` near the imports/exports cpl names, to guess where they would be used/computed. I did that by inspecting eam's folder as well as [this confluence page](https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/961184622/Fields+passed+to+from+component+coupler).

For some fields I put question marks, cause I'm not really sure about their use. When you have a chance (after the holidays), could you put some inline comments in that file, so that I can track down each field in p3/shoc? If a field ends up being unused or not computed, that's also something to write down. Unused ones are great (do nothing), while for not-computed ones we need to see what's a good course of action (might have to set to reasonable values).

@rljacob quick question on the coupler: are the x2a and a2x arrays persistent? Or are they recreated when it's coupling time? I assume it is the former, but I need to be sure. On one hand, I'd like to store the cpl pointers in our surface coupling structures once and for all, rather than re-set pointers every time. On the other hand, for fields we don't compute, I'd like to set a reasonable value at init time, then forget about them completely...

**Comment by singhbalwinder** [comment]
@bartgol : Thanks for setting up the branch and adding comments. I looked through the code and expanded on your comments to add more description. If it looks like too much description, we can trim that down. I have added comments about variable description, units, and how/where it is being used or calculated. There are a few variables which I know where they are being computed/used but I have not added comments about those yet. I wanted to double check before adding those comments.

Please take a look at the [commit](https://github.com/E3SM-Project/scream/compare/bartgol/surface_coupling_2.0#diff-d2920c14265b3aca39e6b32ce6c7e65e58bca8d3ec093e74cd2181ececbdd3a8R55) and let me know if you would like me to change anything else.

**Comment by bartgol** [comment]
@singhbalwinder No such thing as 'too much description'. Especially at this stage, where I'm still trying to understand how all the pieces fit together.

This looks great. Thanks for adding detailed info (including units), it will help a lot.

**Comment by singhbalwinder** [comment]
I have added a few more comments and I think it is complete now (latest [commit](https://github.com/E3SM-Project/scream/compare/bartgol/surface_coupling_2.0#diff-d2920c14265b3aca39e6b32ce6c7e65e58bca8d3ec093e74cd2181ececbdd3a8R55)).

Let me know if I missed anything or if there is anything else needs to be done, thanks!
