### ISSUE TITLE
Semi-Lagrangian Advection in C++

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#830]
If you already have an issue to track this, feel free to close this issue and let me know what it is...

**Comment by ambrad** [comment]
See https://github.com/ambrad/E3SM/pull/27, although there likely will be a new tracking PR on my fork when I sync this work to NHXX in E3SM master.

**Comment by ambrad** [comment]
This is finished in the branch linked above. How and when it will be merged is a remaining issue; the answer likely will depend on timing of v2 tags and scream v1 summit runs.

**Comment by PeterCaldwell** [comment]
Great work! Does this PR affect v2? Or did you just mention v2 because you don't want to add confusion to the repo during this stressful v2 time?

**Comment by ambrad** [comment]
I don't want to merge this branch into E3SM until after the v2 maintenance branches are created and E3SM master becomes essentially the v3 development repo. However, if we end up needing SL on GPU in SCREAM sooner than those maintenance branches are established, I do have a reasonable strategy to get this into E3SM without affecting v2. The alternative of merging the branch just into SCREAM is, as usual, the worst option since that makes upstream merges difficult.

**Comment by PeterCaldwell** [comment]
Gotcha. Ok, let's hold off on merging until it becomes clear that we need to or master gets freed up for v3 work.

**Comment by AaronDonahue** [comment]
Has this been resolved with one of the latest E3SM upstream merges?

**Comment by ambrad** [comment]
Yep!
