### ISSUE TITLE
Create Bundled Array of Tracers

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/scream#859]
We want the AD to be able to create a multi-dimensional array Q (though we should maybe rename it as AdvectedArrays or something), which contains all variables we want to advect by dynamics, SHOC, and physgrid. It should have the first N variables be transported by SHOC and dynamics and the remaining variables just be transported by dynamics.

P3 and rad should be able to subview individual variables from this multi-dimensional array since they don't need most variables in this array.

**Comment by bartgol** [comment]
Some considerations.

We would like individual tracers on phys grid to still be available, but as subviews of the big Q array (for sync and memory reasons). We would also like to have tracers on the physics grid have layout `(ncols,ntracers,nlevs)`.

These two requirements add some complexities to Fields handling:

- First, we need to have the field repo to _not_ allocate certain fields, and instead create them as subviews of other fields. More specifically, if a field has the label, say, TRACER, then it should not be allocated; instead, its view should be a subview of a slice of the Q field.
- Second, the layout `(nc,nt,nl)` makes subviewing a bit more involved, in that a slice of the form `(:,itracer,:)` has a strided layout. This is not too bad, since virtually all our kernels start by subviewing their views at a particular column; therefore, even if `qv` had strided layout, subviewing it at a particular column should restore a contiguous layout.
- Third, we need to be aware that a view's size may no longer coincide with the span in memory (the two are equal in case of contiguous memory, but they are not for strided views). In general, the `FieldAllocProperties` metadata could be improved to contain some more information regarding how the field is laid out in memory.

**Comment by jeff-cohere** [comment]
The tracers field would be stored as an ordinary field in the field repo, right?

Maybe we can add a new version of `register_field` that specifies a "parent" field and the necessary info for creating a subview of that parent. Do you think that's sufficient to give access to individual tracers to the different atmosphere processes? (Aside from the additional assumptions you mention).

**Comment by bartgol** [comment]
Yes, Q would be an ordinary field in the repo.

As for the special version of `register_field`, how much knowledge of the "parent" field would be required at registration time? If, say, P3 registers `qv`, it is a bit too much to ask P3 to know the sizes of Q, and which slice would `qv` be. I think this route would make the code a bit more intertwined.

It is true that the big Q is not just the juxtaposition of the different qi's, b/c of the layout not being (nt,ncols,nlevs), so the repo cannot handle the group "agnostically", creating the big rank+1 field and each individual field as a subview. In particular, the repo would need to know which index is used to represent each field; e.g., `(ifield,:,:)` vs `(:, ifield, :)`. However, I think it's ok (for now) to make an exception in the repo to handle this particular case (the tracers): the repo will allocate Q with dims (nc,nt,nlevs), with nt equal to the number of fields with the `ADVECTED` tag attached. Then, the repo will proceed to create all the individual fields as subviews.

In the future we might generalize, and make the repo bundle all groups (e.g., STATE maybe?) in the same way: `(ncols, group_size, ...)`, at least for phys grid. However, I don't know how many other occurrences of this need (namely, the need of having bundled fields) we'll have, so I'm fine adding this one exception for tracers inside the field repo allocation code.

**Comment by jeff-cohere** [comment]
Makes sense. So, provided we have this special treatment of the tracer fields: how would we define the individual tracer fields? Do we register them, adding each to an `ADVECTED` field group (for example), and then the big Q field is created from all `ADVECTED` fields, and subview fields are created?

**Comment by bartgol** [comment]
That's what I had in mind. As long as atm processes provide the 'ADVECTED' group tag at registration time, the repo has all it needs to do the rest: count them, allocate Q, create subviews for qi's.
