### ISSUE TITLE
Fixing Radiation interface to take LayoutRight input views

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/scream#951]
Our radiation interface will probably *not* work with padded views as-is. We currently have a check in the interface to make sure that fields we get from the Field Manager are not padded, and the code will abort if padded views are encountered. It is not clear what would happen if we tried to use padded views in RRTMGP.

**Comment by tcclevenger** [comment]
Update: `atmosphere_radiation.cpp` currently is loading in data into a Fortran-style YAKL array (data layout where dim1 is the fastest index, i.e., column entries are contiguous in memory), then wrapping a Kokkos view (`LayoutRight`) around that data. Since the this view has dim2 as the fastest index, the entries were not index correctly. This is _currently_ not an issue, since in the `rrtmgp_standalone` test then immediately wraps the data back to a YAKL array, but it will be an issue moving forward when we need to access/manipulate the Kokkos view and/or when the FM inputs do not originally come from Fortran-style data.

PR https://github.com/E3SM-Project/scream/pull/1047 addresses this issue by just creating a copy of the data in LayoutRight format. Ideally we do not want to copy data, but with the current RRTMGP structure not sure there is a way around this.

This does now mean that packing is no issue.

**Comment by tcclevenger** [comment]
I've updated the title and linked the PR.
